### ISSUE TITLE
Issue with intent_service.py context_manager

### ISSUE THREAD

**Issue by Nevyn579** [MycroftAI/mycroft-core#1045]
Line 227:  context_manager=self.context_manager

Attempting to utilize skills like skill-desktop-launcher "open firefox" results in this issue.
This is replicated in other skills as well.

Current Enclosure:
Laptop:  Dell Latitude 2120
OS:  Kubuntu 17.04

Logs:
2017-09-01 09:38:43,699 - Skills - DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "en-US", "session": "10471646-0a85-41da-895b-960f34857e75", "utterances": ["open firefox"]}, "context": null}
2017-09-01 09:38:43,775 - mycroft.skills.intent_service - ERROR - 
Traceback (most recent call last):
  File "/home/brendan/mycroft-core/mycroft/skills/intent_service.py", line 227, in handle_utterance
    context_manager=self.context_manager))
StopIteration
2017-09-01 09:38:43,789 - Skills - DEBUG - {"type": "intent_failure", "data": {"lang": "en-US", "utterance": "open firefox"}, "context": null}
2017-09-01 09:38:43,791 - mycroft.skills.padatious_service - DEBUG - Padatious fallback attempt: open firefox
2017-09-01 09:38:43,792 - mycroft.skills.core - INFO - Exception in fallback: max() arg is an empty sequence
2017-09-01 09:38:43,793 - fallback-wolfram-alpha__init__ - DEBUG - WolframAlpha fallback attempt: open firefox
2017-09-01 09:38:43,794 - fallback-wolfram-alpha__init__ - DEBUG - Unknown intent: open firefox
2017-09-01 09:38:43,796 - mycroft.skills.core - WARNING - No fallback could handle intent.
2017-09-01 09:38:43,802 - Skills - DEBUG - {"type": "complete_intent_failure", "data": {}, "context": null}
2017-09-01 09:38:43,840 - Skills - DEBUG - {"type": "speak", "data": {"utterance": "Sorry, I didn't catch that. Please rephrase your request."}, "context": null}

**Comment by forslund** [comment]
Hi, I don't think this is a problem with the intent_handler.

desktop launcher has some external dependencies that needs to be met. I could reproduce the issue and for me it was that the location of the needed gio module wasn't found in the correct location.

**Comment by forslund** [comment]
Can you do a `locate gio/__init__.py` and tell me the result?

**Comment by Nevyn579** [comment]
Hi.  Sorry for the delayed response.  I had some family stuff happen.  Here is the location of gio:
~/mycroft-core/scripts$ locate gio/__init__.py
/usr/lib/python2.7/dist-packages/gtk-2.0/gio/__init__.py
/usr/lib/python2.7/dist-packages/gtk-2.0/gio/__init__.pyc

**Comment by forslund** [comment]
No problem at all.

It's looking the same on my machine. I had to modify the desktop-launcher skill to get it working.

adding 
```python
        sys.path.append("/usr/lib/python2.7/dist-packages/gtk-2.0")
```

under the line
```python
        sys.path.append("/usr/lib/python2.7/dist-packages")
```

to the skill helped me. I'll create a PR with this change for the skill and will look into some more generic solution for the future.

**Comment by whatishappening123** [comment]
I am also having a similar issue with this file.
I am using a macbook pro with a Ubuntu 16.04.2  

Currently I am attempting to run your context example from [here](https://github.com/MycroftAI/mycroft-core/wiki/Conversational-context). I have added the necessary vocab files that should correspond with the file. When I say "Hey mycroft, bring me some tea" the intent returns as not found. To make sure other custom skills work I have edited and made changes to the hello world skill, and mycroft responds to those changes.

Ive attached logs from the skills portion of start.sh 

Any help would be great. Thanks


017-09-26 09:45:52,924 - mycroft.configuration - INFO - Loading configuration: /etc/mycroft/mycroft.conf
2017-09-26 09:45:52,924 - mycroft.configuration - DEBUG - Configuration '/etc/mycroft/mycroft.conf' not found
2017-09-26 09:45:52,924 - mycroft.configuration - DEBUG - Configuration '/home/steve/.mycroft/mycroft.conf' not found
2017-09-26 09:45:52,924 - mycroft.configuration - INFO - Loading configuration: /home/steve/.mycroft/mycroft.conf
2017-09-26 09:45:52,925 - mycroft.configuration - DEBUG - Configuration '/home/steve/.mycroft/mycroft.conf' not found
2017-09-26 09:45:52,925 - mycroft.configuration - DEBUG - Configuration '/home/steve/.mycroft/mycroft.conf' not found
2017-09-26 09:46:06,608 - Skills - DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "en-us", "utterances": ["bring me some tea"]}, "context": null}
2017-09-26 09:46:06,610 - Skills - DEBUG - {"type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": 1724922955324666750, "utterances": ["bring me some tea"]}, "context": null}
2017-09-26 09:46:06,612 - Skills - DEBUG - {"type": "skill.converse.response", "data": {"skill_id": 1724922955324666750, "result": false}, "context": null}
2017-09-26 09:46:06,712 - Skills - DEBUG - {"type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": -7077859893790634714, "utterances": ["bring me some tea"]}, "context": null}
2017-09-26 09:46:06,714 - Skills - DEBUG - {"type": "skill.converse.response", "data": {"skill_id": -7077859893790634714, "result": false}, "context": null}
2017-09-26 09:46:06,820 - mycroft.skills.intent_service - ERROR - 
Traceback (most recent call last):
  File "/home/steve/mycroft-core/mycroft/skills/intent_service.py", line 239, in handle_utterance
    context_manager=self.context_manager))
StopIteration
2017-09-26 09:46:06,822 - Skills - DEBUG - {"type": "intent_failure", "data": {"lang": "en-us", "utterance": "bring me some tea"}, "context": null}
2017-09-26 09:46:06,822 - mycroft.skills.padatious_service - DEBUG - Padatious fallback attempt: bring me some tea
2017-09-26 09:46:06,822 - mycroft.skills.core - INFO - Exception in fallback: max() arg is an empty sequence
2017-09-26 09:46:06,825 - mycroft.skills.core - WARNING - No fallback could handle intent.
2017-09-26 09:46:06,826 - Skills - DEBUG - {"type": "complete_intent_failure", "data": {}, "context": null}
2017-09-26 09:46:06,866 - Skills - DEBUG - {"type": "speak", "data": {"utterance": "Sorry, I didn't catch that. Please rephrase your request."}, "context": null}

**Comment by forslund** [comment]
The skill has been updated and there's been no more responses from the original author. Closing
