### ISSUE TITLE
OSError: [Errno 13] Permission denied - SOLVED

### ISSUE THREAD

**Issue by fireblox** [MycroftAI/mycroft-core#1186]
I try to bash dev_setup.sh and it gives me this error.

Exception:
Traceback (most recent call last):
  File "/home/fireblox/.virtualenvs/mycroft/lib/python2.7/site-packages/pip-7.1.2-py2.7.egg/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/home/fireblox/.virtualenvs/mycroft/lib/python2.7/site-packages/pip-7.1.2-py2.7.egg/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/home/fireblox/.virtualenvs/mycroft/lib/python2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/home/fireblox/.virtualenvs/mycroft/lib/python2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/home/fireblox/.virtualenvs/mycroft/lib/python2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/home/fireblox/.virtualenvs/mycroft/lib/python2.7/site-packages/pip-7.1.2-py2.7.egg/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/home//.virtualenvs/mycroft/lib/python2.7/site-packages/netifaces-0.10.5-py2.7.egg-info/dependency_links.txt'

**Comment by fireblox** [comment]
acctualy, i could resolve the problem, using chmod 777 to the folder, now it downloads the netifaces 0.10.6 and stop saying:
 fatal: could not create work tree dir 'mimic': Permission denied

**Comment by fireblox** [comment]
SOLVED - 

     echo "Usage: dev_setup.sh [options]"
        echo
        echo "Options:"
        echo "    -r, --allow-root  Allow to be run as root (e.g.
