### ISSUE TITLE
dependencies for openSUSE Tumbleweed

### ISSUE THREAD

**Issue by JenaPlinsky** [MycroftAI/mycroft-core#1330]
Hi guys 
... I can not find these dependencies for openSUSE Tumbleweed can someone help me ?

- virtualenvwrapper

- libglib2.0-devel

- libssl-devel

- portaudio19-devel

**Comment by ChrisFoster4** [comment]
After some Googling/DDGing I think I have found the packages. I'm not running openSuse so I can't test building with  these packages but I hope this helps. Post any further issues you have.

[virtualenvwrapper](https://opensuse.pkgs.org/42.3/opensuse-oss/python-virtualenvwrapper-4.3.2-5.1.noarch.rpm.html)

[libglib2.0-devel](https://software.opensuse.org/package/glib2-devel)

[libssl-devel](https://opensuse.pkgs.org/42.2/opensuse-update-oss/libressl-devel-2.5.3-5.6.1.x86_64.rpm.html)

portaudio19-devel - Should be installable as libportaudio2. I found it in [this ](https://en.opensuse.org/Archive:Package_list_12.3)package list and [this site](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_linux) told me that it may be called "libportaudio2" in non Debian distros.

**Comment by ChrisFoster4** [comment]
Ok I have got it to run in an openSuse Tumbleweed virtual machine by adding the approriate zypper commands to dev_setup.sh. I also have to run the `update-dev.sh` script before running the `start-mycroft.sh debug` script.Could you try using the modified dev_setup.sh I have attached to get Mycroft working. Good luck.
[dev_setup.zip](https://github.com/MycroftAI/mycroft-core/files/1591639/dev_setup.zip)

**Comment by JenaPlinsky** [comment]
@ChrisFoster4 
unfortunately I still have problems anyway thank you very much for your help

```
[sudo] password di root: 
Caricamento dati del repository in corso...
Lettura dei pacchetti installati in corso...
'glib2-devel' è già installato.
Nessun aggiornamento candidato per 'glib2-devel-2.54.2-361.1.x86_64'. La versione più recente disponibile è già installata.
'python-virtualenvwrapper' è già installato.
Nessun aggiornamento candidato per 'python-virtualenvwrapper-4.7.1-2.3.noarch'. La versione più recente disponibile è già installata.
'libressl-devel' è già installato.
Nessun aggiornamento candidato per 'libressl-devel-2.6.3-2.1.x86_64'. La versione più recente disponibile è già installata.
'pkg-config' è già installato.
Nessun aggiornamento candidato per 'pkg-config-0.29.2-59.19.x86_64'. La versione più recente disponibile è già installata.
'python' è già installato.
Nessun aggiornamento candidato per 'python-2.7.14-1.1.x86_64'. La versione più recente disponibile è già installata.
'python-setuptools' non è stato trovato nei nomi dei pacchetti. Viene eseguito il tentativo di ricerca per funzionalità.
Il pacchetto 'python2-setuptools', che fornisce 'python-setuptools', è già installato.
'python-devel' è già installato.
Nessun aggiornamento candidato per 'python-devel-2.7.14-1.2.x86_64'. La versione più recente disponibile è già installata.
'libtool' è già installato.
Nessun aggiornamento candidato per 'libtool-2.4.6-4.78.x86_64'. La versione più recente disponibile è già installata.
'automake' è già installato.
Nessun aggiornamento candidato per 'automake-1.15.1-2.1.noarch'. La versione più recente disponibile è già installata.
'bison' è già installato.
Nessun aggiornamento candidato per 'bison-3.0.4-4.7.x86_64'. La versione più recente disponibile è già installata.
'libjpeg-devel' non è stato trovato nei nomi dei pacchetti. Viene eseguito il tentativo di ricerca per funzionalità.
Il pacchetto 'libjpeg62-devel', che fornisce 'libjpeg-devel', è già installato.
'autoconf' è già installato.
Nessun aggiornamento candidato per 'autoconf-2.69-15.8.noarch'. La versione più recente disponibile è già installata.
'libffi-devel' è già installato.
Nessun aggiornamento candidato per 'libffi-devel-3.2.1.git259-4.2.x86_64'. La versione più recente disponibile è già installata.
'python-gobject-devel' è già installato.
Il pacchetto 'python-gobject-devel' non è disponibile nei repository. Impossibile eseguirne la reinstallazione, l'upgrade o il downgrade.
'libicu-devel' è già installato.
Nessun aggiornamento candidato per 'libicu-devel-59.1-2.2.x86_64'. La versione più recente disponibile è già installata.
'jq' è già installato.
Nessun aggiornamento candidato per 'jq-1.5-10.1.x86_64'. La versione più recente disponibile è già installata.
'swig' è già installato.
Nessun aggiornamento candidato per 'swig-3.0.12-3.1.x86_64'. La versione più recente disponibile è già installata.
'git' è già installato.
Nessun aggiornamento candidato per 'git-2.15.1-1.2.x86_64'. La versione più recente disponibile è già installata.
'curl' è già installato.
Nessun aggiornamento candidato per 'curl-7.57.0-1.1.x86_64'. La versione più recente disponibile è già installata.
'mpg123' è già installato.
Nessun aggiornamento candidato per 'mpg123-1.25.8-1.1.x86_64'. La versione più recente disponibile è già installata.
'flac' è già installato.
Nessun aggiornamento candidato per 'flac-1.3.2-1.4.x86_64'. La versione più recente disponibile è già installata.
'python-curses' è già installato.
Nessun aggiornamento candidato per 'python-curses-2.7.14-1.1.x86_64'. La versione più recente disponibile è già installata.
'screen' è già installato.
Nessun aggiornamento candidato per 'screen-4.6.2-2.2.x86_64'. La versione più recente disponibile è già installata.
'libportaudio2' è già installato.
Nessun aggiornamento candidato per 'libportaudio2-190600_20161030-2.2.x86_64'. La versione più recente disponibile è già installata.
'libfann-devel' è già installato.
Nessun aggiornamento candidato per 'libfann-devel-2.2.0-2.3.x86_64'. La versione più recente disponibile è già installata.
'python2-s3transfer' è già installato.
Nessun aggiornamento candidato per 'python2-s3transfer-0.1.11-1.1.noarch'. La versione più recente disponibile è già installata.
Risoluzione dipendenze dei pacchetti in corso...

Nessuna operazione da eseguire.
Caricamento dati del repository in corso...
Lettura dei pacchetti installati in corso...
'pattern:devel_basis' è già installato.
Nessun aggiornamento candidato per 'pattern:devel_basis-20170518-6.1.x86_64'. La versione più recente disponibile è già installata.
Risoluzione dipendenze dei pacchetti in corso...

Nessuna operazione da eseguire.
Caricamento dati del repository in corso...
Lettura dei pacchetti installati in corso...
's3cmd' è già installato.
Nessun aggiornamento candidato per 's3cmd-2.0.0-1.5.noarch'. La versione più recente disponibile è già installata.
Risoluzione dipendenze dei pacchetti in corso...

Nessuna operazione da eseguire.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 7, in <module>
    from virtualenv import main
ImportError: No module named 'virtualenv'

```

**Comment by JenaPlinsky** [comment]
**start-mycroft.sh debug**
I can not understand if the script **cli** is working ...
   ...[python /home/Shared/Settings/Script/mycroft-core/mycroft/client/text/main.py]

```
Ivan@UltrabookSamsung:/home/Shared/Settings/Script/mycroft-core> ./start-mycroft.sh debug
Starting all mycroft-core services
Initializing...
Starting background service bus
Starting background service skills
Starting background service audio
Starting background service voice
Starting cli
Ivan@UltrabookSamsung:/home/Shared/Settings/Script/mycroft-core> 
```
how can I do if it works?

-----------------------------------------------------------------------------------------------------------------------------


Plasmiid:
in my case, which location of Mycroft-core should I use?
   - in the Home folder there is nothing to do with mycroft
   - the folder where I compiled Mycroft-core is: /home/Shared/Settings/Script/mycroft-core
   - I also found this folder /opt/mycroft 
   - or this /home/Ivan/.virtualenvs/mycroft
![screenshot_20171230_082443](https://user-images.githubusercontent.com/24593950/34452464-df36bd84-ed3f-11e7-944a-2f64d6f3a9cf.png)

**Comment by JenaPlinsky** [comment]
Test
```
Ivan@UltrabookSamsung:/home/Shared/Settings/Script/mycroft-core/mycroft/client/text> python2.7 main.py

Traceback (most recent call last):
  File "main.py", line 34, in <module>
    import mycroft.version                                      # nopep8
ImportError: No module named mycroft.version
```

**Comment by forslund** [comment]
If you have the possibility please try out PR #1355 which seems to work (tested on a fresh Tumbleweed installation in a virtual machine)

**Comment by forslund** [comment]
#1355 has been merged and should make the Tumbleweed setup easier.

**Comment by forslund** [comment]
Closing this as it's been fixed.
