### ISSUE TITLE
python 3.6 TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by femans** [MycroftAI/mycroft-core#1462]
I installed everything using dev_setup on an arch system, and after some hacks to some scripts (described in other tickets), I got to the point of running the code. 
I ran `./start-mycroft.sh` or `python  ./mycroft/client/text/main.py` and this is my output. It seems to be a python version problem. 
This is something I believe should be fixed by the installer before running the code.
output:

```
Starting cli
b''
b''
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xor/projects/mycroft-core/mycroft/configuration/config.py", line 128, in load_local
    LOG.debug("Configuration {} loaded".format(path))
  File "/home/xor/projects/mycroft-core/mycroft/util/log.py", line 32, in method
    cls._log(fn, *args, **kwargs)
  File "/home/xor/projects/mycroft-core/mycroft/util/log.py", line 108, in _log
    func(cls.create_logger(name), *args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1294, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 998, in emit
    self.handleError(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 915, in handleError
    sys.stderr.write('--- Logging error ---\n')
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xor/projects/mycroft-core/mycroft/client/text/main.py", line 1055, in <module>
    start_mic_monitor(os.path.join(get_ipc_directory(), "mic_level"))
  File "/home/xor/projects/mycroft-core/mycroft/util/signal.py", line 38, in get_ipc_directory
    config = mycroft.configuration.Configuration.get()
  File "/home/xor/projects/mycroft-core/mycroft/configuration/config.py", line 207, in get
    return Configuration.load_config_stack(configs, cache)
  File "/home/xor/projects/mycroft-core/mycroft/configuration/config.py", line 221, in load_config_stack
    configs = [LocalConf(DEFAULT_CONFIG), RemoteConf(),
  File "/home/xor/projects/mycroft-core/mycroft/configuration/config.py", line 113, in __init__
    self.load_local(path)
  File "/home/xor/projects/mycroft-core/mycroft/configuration/config.py", line 130, in load_local
    LOG.error("Error loading configuration '{}'".format(path))
  File "/home/xor/projects/mycroft-core/mycroft/util/log.py", line 32, in method
    cls._log(fn, *args, **kwargs)
  File "/home/xor/projects/mycroft-core/mycroft/util/log.py", line 108, in _log
    func(cls.create_logger(name), *args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 998, in emit
    self.handleError(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 915, in handleError
    sys.stderr.write('--- Logging error ---\n')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by femans** [comment]
hang on, after deleting the virtualenv and reinstalling everything, python 2.7 was installed. I am closing this issue again.

**Comment by suyash248** [comment]
I've already tried to remove and re-create the virtualenv. But I'm still facing the similar issue. I'm using python 3.6 and virutalenv is activated.

**Comment by forslund** [comment]
Hi @suyash248 is the error exactly the same or just similar? If it's differs it would help to have the exact log you're getting.

**Comment by suyash248** [comment]
Hi @forslund, I'm getting exactly the same error, here are the logs - 

`
{"message": "Initializing logger..."}
{"timestamp": "2018-08-23T06:42:14.040608Z", "message": "Initializing logger...", "host": "suyash.local", "path": "/Users/suyash.soni/Code/tnt/smartview_flask/app.py", "tags": [], "level": "INFO", "logger": "python-logstash-logger", "stack_info": null}

--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/handlers.py", line 633, in emit
    s = self.makePickle(record)
  File "/Users/suyash.soni/Code/tnt/smartview_flask/.env/lib/python3.6/site-packages/logstash/handler_tcp.py", line 26, in makePickle

    return str.encode(self.formatter.format(record)) + b'\n'

TypeError: descriptor 'encode' requires a 'str' object but received a 'bytes'

Call stack:
  File "/Users/suyash.soni/Code/tnt/smartview_flask/.env/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/Users/suyash.soni/Code/tnt/smartview_flask/.env/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/Users/suyash.soni/Code/tnt/smartview_flask/.env/lib/python3.6/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/Users/suyash.soni/Code/tnt/smartview_flask/.env/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/Users/suyash.soni/Code/tnt/smartview_flask/.env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/Users/suyash.soni/Code/tnt/smartview_flask/.env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 544, in manage_workers
    self.spawn_workers()
  File "/Users/suyash.soni/Code/tnt/smartview_flask/.env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 611, in spawn_workers
    self.spawn_worker()
  File "/Users/suyash.soni/Code/tnt/smartview_flask/.env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/Users/suyash.soni/Code/tnt/smartview_flask/.env/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/Users/suyash.soni/Code/tnt/smartview_flask/.env/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/Users/suyash.soni/Code/tnt/smartview_flask/.env/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/suyash.soni/Code/tnt/smartview_flask/.env/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/suyash.soni/Code/tnt/smartview_flask/.env/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/suyash.soni/Code/tnt/smartview_flask/.env/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/suyash.soni/Code/tnt/smartview_flask/.env/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/suyash.soni/Code/tnt/smartview_flask/wsgi.py", line 1, in <module>
    from app import app as application
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/suyash.soni/Code/tnt/smartview_flask/app.py", line 112, in <module>
    init_logger()
  File "/Users/suyash.soni/Code/tnt/smartview_flask/app.py", line 89, in init_logger
    Logger.info('Initializing logger...')
Message: 'Initializing logger...'
Arguments: ()
{"message": "Fetching employees..."}
`
