### ISSUE TITLE
Zeroconf has dropped support for python 2

### ISSUE THREAD

**Issue by tlc** [MycroftAI/mycroft-core#1482]
Recent clone of the dev tree on Ubuntu 16.04.

I was looking into this exception in the logs

```
Traceback (most recent call last):
  File "/home/troy/MYCROFT/source/mycroft/audio/main.py", line 115, in load_services
    *descriptor["info"])
  File "/home/troy/MYCROFT/source/mycroft/audio/services/chromecast/__init__.py", line 18, in <module>
    import pychromecast
  File "/home/troy/.virtualenvs/mycroft/local/lib/python2.7/site-packages/pychromecast/__init__.py", line 15, in <module>
    from .discovery import discover_chromecasts
  File "/home/troy/.virtualenvs/mycroft/local/lib/python2.7/site-packages/pychromecast/discovery.py", line 6, in <module>
    from zeroconf import ServiceBrowser, Zeroconf
  File "/home/troy/.virtualenvs/mycroft/local/lib/python2.7/site-packages/zeroconf.py", line 23, in <module>
    import enum
ImportError: No module named enum
```
Hmm.

```
$ python -c "import zeroconf"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/troy/.virtualenvs/mycroft/local/lib/python2.7/site-packages/zeroconf.py", line 23, in <module>
    import enum
ImportError: No module named enum
```

When I saw that according to the README, zeroconf has dropped support for python 2.

https://github.com/jstasiak/python-zeroconf

**Comment by tlc** [comment]
Zeroconf was pulled in by pychromecast.

Adding this to requirements.txt fixed it.

```
# pychromecast pulls in zeroconf
# which dropped python2 support in 0.20.0
zeroconf<0.20.0
```

**Comment by DarthSpock** [comment]
Why are you still using python 2? Support was dropped because the Python developers dropped support. You can use it if you want but unless you have something that's screaming for backwards-compatibility even after recompiling your code for Python 3, you should upgrade. See more about it [here](https://wiki.python.org/moin/Python2orPython3)

**Comment by el-tocino** [comment]
Mycroft is moving to python3, check some of the recent PR's for more.

**Comment by forslund** [comment]
We've moved over to python 3 (About time!) now so this shouldn't be an issue anymore. Closing.

Also, well be doing a review of our package versions shortly.
