### ISSUE TITLE
An error occurred while processing a request in Skill Installer Skill

### ISSUE THREAD

**Issue by tomasloksa** [MycroftAI/mycroft-core#1516]
I'm running Mycroft on Linux Mint 18.3, Mycroft v18.2.3 beta
I get this error whenever i try to install a skill (tried calculator, dice, speed test).
After a fresh install i managed to install spotify-skill. After that i was just trying out commands like weather, singing, alaram etc. and now i can't manage to install anything at all.

Here's the skills.log :

```
21:34:46.481 - __main__:handle_wakeword:57 - INFO - Wakeword Detected: hey mycroft
21:34:48.484 - __main__:handle_utterance:62 - INFO - Utterance: [u'install calculator']

21:34:48.964 - mycroft.skills.core:wrapper:608 - ERROR - An error occurred while processing a request in Skill Installer Skill
Traceback (most recent call last):
  File "/home/tomas/Programs/mycroft-core/mycroft/skills/core.py", line 599, in wrapper
    handler(message)
  File "/opt/mycroft/skills/skill-installer/__init__.py", line 174, in install
    skills = self.search_for_skill(search, self.get_skill_list())
  File "/opt/mycroft/skills/skill-installer/__init__.py", line 96, in get_skill_list
    self.ansi_escape.sub('', check_output([BIN, 'list'])).split('\n')
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['/home/tomas/Programs/mycroft-core/msm/msm', 'list']' returned non-zero exit status 111
21:34:48.966 - SKILLS - DEBUG - {"type": "speak", "data": {"expect_response": false, "utterance": "An error occurred while processing a request in Skill Installer Skill"}, "context": {"client_name": "mycroft_listener", "ident": "1522438486.48-8684732703421927695", "target": null}}
21:34:48.967 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
21:34:48.968 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"exception": "", "name": "SkillInstallerSkill.install"}, "context": null}
```

**Comment by cowang4** [comment]
It looks like the Mycroft Skills Manager (msm) failed for some reason. Can you run
`msm/msm list` from the `mycroft-core` folder for us and post what it outputs?

**Comment by forslund** [comment]
At one time I've experienced an rate limiting issue on https://raw.githubusercontent.com/ (which is used to fetch the skill list), could be the same thing happening to you.

**Comment by forslund** [comment]
I've opened up a PR in skill-installer giving more feedback about the error. Is it still an issue for you?

**Comment by MatthewScholefield** [comment]
Closing this since we've recently rewritten msm which uses a new mechanism for listing info which shouldn't get rate limited. Also, there's been no activity for 30 days.
