### ISSUE TITLE
TypeError in lock Signal class when listener sleeps ?

### ISSUE THREAD

**Issue by tlc** [MycroftAI/mycroft-core#1538]
```
04:17:28.840 - mycroft.messagebus.client.ws:on_open:61 - INFO - Connected
04:17:30.746 - mycroft.client.speech.mic:listen:523 - DEBUG - Waiting for wake word...
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/client/speech/main.py", line 178, in <module>
    main()
  File "/home/pi/mycroft-core/mycroft/client/speech/main.py", line 171, in main
    loop.run()
  File "/home/pi/mycroft-core/mycroft/client/speech/listener.py", line 333, in run
    time.sleep(1)
  File "/home/pi/mycroft-core/mycroft/lock/__init__.py", line 63, in __call__
    self.__previous_func(signame, sf)
TypeError: 'int' object is not callable
```
Not sure what's going on here.  The listener.py run() loop has a time.sleep(1)
A lock.Signal() class is called and hits an error.

The Signal() class has "python 3+" in all the comments.  But we're still running python2?

**Comment by tlc** [comment]
Fix.

```
$ git diff .
diff --git a/mycroft/lock/__init__.py b/mycroft/lock/__init__.py
index f3eb43c..a7a5e3e 100644
--- a/mycroft/lock/__init__.py
+++ b/mycroft/lock/__init__.py
@@ -59,7 +59,7 @@ class Signal(object):  # python 3+ class Signal
         there is a previously defined handler call it.
         '''
         self.__user_func()  # call user function
-        if self.__previous_func:
+        if self.__previous_func and callable(self.__previous_func):
             self.__previous_func(signame, sf)
 
     #
```

**Comment by tlc** [comment]
Ah, this was handled a different way a couple days ago.  Closing
