### ISSUE TITLE
`./start-mycroft.sh audiotest` on Ubuntu 16.04 LTS consistently fails with `ImportError: cannot import name '_args_from_interpreter_flags'`

### ISSUE THREAD

**Issue by KathyReid** [MycroftAI/mycroft-core#1640]
Reported in the Community Forum [here](https://community.mycroft.ai/t/audiotest-is-returning-importerror-cannon-import-name-args-from-interpreter-flags/3826/4)

## running `./start-mycroft.sh audiotest` on Ubuntu 16.04 LTS consistently fails with `ImportError: cannot import name '_args_from_interpreter_flags'`

* Mycroft for Linux, `git` install
* 18.2.8b
* `./dev_setup.sh` has been run recently

## to replicate

`./start-mycroft.sh audiotext`

## error message

```bash
kathyreid@kathyreid-N76VZ:~/Dropbox/PHPworkspace/mycroft-core$ ./start-mycroft.sh audiotest
Initializing...
Starting audiotest
Traceback (most recent call last):
  File "/home/kathyreid/Dropbox/PHPworkspace/mycroft-core/mycroft/util/audio_test.py", line 17, in <module>
    from speech_recognition import Recognizer
  File "/home/kathyreid/Dropbox/PHPworkspace/mycroft-core/.venv/lib/python3.5/site-packages/speech_recognition/__init__.py", line 8, in <module>
    import subprocess
  File "/usr/lib/python3.5/subprocess.py", line 364, in <module>
    import signal
  File "/home/kathyreid/Dropbox/PHPworkspace/mycroft-core/mycroft/util/signal.py", line 21, in <module>
    import mycroft
  File "/home/kathyreid/Dropbox/PHPworkspace/mycroft-core/mycroft/__init__.py", line 20, in <module>
    from mycroft.skills.core import MycroftSkill, FallbackSkill, \
  File "/home/kathyreid/Dropbox/PHPworkspace/mycroft-core/mycroft/skills/core.py", line 33, in <module>
    from mycroft.client.enclosure.api import EnclosureAPI
  File "/home/kathyreid/Dropbox/PHPworkspace/mycroft-core/mycroft/client/enclosure/__init__.py", line 26, in <module>
    from mycroft.client.enclosure.display_manager import \
  File "/home/kathyreid/Dropbox/PHPworkspace/mycroft-core/mycroft/client/enclosure/display_manager.py", line 40, in <module>
    from mycroft.messagebus.client.ws import WebsocketClient
  File "/home/kathyreid/Dropbox/PHPworkspace/mycroft-core/mycroft/messagebus/client/ws.py", line 17, in <module>
    from multiprocessing.pool import ThreadPool
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 26, in <module>
    from . import util
  File "/usr/lib/python3.5/multiprocessing/util.py", line 17, in <module>
    from subprocess import _args_from_interpreter_flags
ImportError: cannot import name '_args_from_interpreter_flags'
```

**Comment by forslund** [comment]
I tested that briefly and I think it's some sort of namespace conflict. Moving the audio_test.py to another folder lets the test run again. (I tested moving it to the mycroft/audio folder)

**Comment by forslund** [comment]
You could try the workaround in the branch [bugfix/audio-test](https://github.com/MycroftAI/mycroft-core/tree/bugfix/audio-test)
