### ISSUE TITLE
msm requires future

### ISSUE THREAD

**Issue by ndarilek** [MycroftAI/mycroft-core#1726]
If msm is installed from pip3 using:

`$ pip3 install msm`

it fails unless you run:

`$ pip3 install future`

Not sure if this method is officially supported, but things seem to work fine once future is installed, so maybe it could be added as an msm dependency?

**Comment by MatthewScholefield** [comment]
What fails exactly?

**Comment by ndarilek** [comment]
The easiest way to reproduce this if you have Docker installed is to run 
an alpine:latest container and do:

```bash
# apk add python3-dev
...
# pip3 install msm
...
# msm -h
Traceback (most recent call last):
   File "/usr/bin/msm", line 11, in <module>
     load_entry_point('msm==0.5.17', 'console_scripts', 'msm')()
   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", 
line 565, in load_entry_point
     return get_distribution(dist).load_entry_point(group, name)
   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", 
line 2631, in load_entry_point
     return ep.load()
   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", 
line 2291, in load
     return self.resolve()
   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", 
line 2297, in resolve
     module = __import__(self.module_name, fromlist=['__name__'], level=0)
   File "/usr/lib/python3.6/site-packages/msm/__init__.py", line 22, in 
<module>
     from .exceptions import *
   File "/usr/lib/python3.6/site-packages/msm/exceptions.py", line 24, 
in <module>
     from future.utils import raise_from
ModuleNotFoundError: No module named 'future'
# pip3 install future
...
# msm -h
Traceback (most recent call last):
   File "/usr/lib/python3.6/site-packages/git/__init__.py", line 83, in 
<module>
     refresh()
   File "/usr/lib/python3.6/site-packages/git/__init__.py", line 73, in 
refresh
     if not Git.refresh(path=path):
   File "/usr/lib/python3.6/site-packages/git/cmd.py", line 290, in refresh
     raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
     - be included in your $PATH
     - be set via $GIT_PYTHON_GIT_EXECUTABLE
     - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by 
setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
     - quiet|q|silence|s|none|n|0: for no warning or exception
     - warn|w|warning|1: for a printed warning
     - error|e|raise|r|2: for a raised exception

Example:
     export GIT_PYTHON_REFRESH=quiet


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
   File "/usr/bin/msm", line 11, in <module>
     load_entry_point('msm==0.5.17', 'console_scripts', 'msm')()
   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", 
line 565, in load_entry_point
     return get_distribution(dist).load_entry_point(group, name)
   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", 
line 2631, in load_entry_point
     return ep.load()
   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", 
line 2291, in load
     return self.resolve()
   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", 
line 2297, in resolve
     module = __import__(self.module_name, fromlist=['__name__'], level=0)
   File "/usr/lib/python3.6/site-packages/msm/__init__.py", line 22, in 
<module>
     from .exceptions import *
   File "/usr/lib/python3.6/site-packages/msm/exceptions.py", line 25, 
in <module>
     from git import GitError
   File "/usr/lib/python3.6/site-packages/git/__init__.py", line 85, in 
<module>
     raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
     - be included in your $PATH
     - be set via $GIT_PYTHON_GIT_EXECUTABLE
     - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by 
setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
     - quiet|q|silence|s|none|n|0: for no warning or exception
     - warn|w|warning|1: for a printed warning
     - error|e|raise|r|2: for a raised exception

Example:
     export GIT_PYTHON_REFRESH=quiet
```

The second exception is expected since Git isn't installed in this 
container, but it seems like msm should at least handle installing `future`.

Thanks.

**Comment by penrods** [comment]
I might be mixing things up, but I think this was resolved recently -- I recall a "future" dependency being removed in some of our tool chain.  Can you verify?

**Comment by j1nx** [comment]
Recently discovered;

Future is a compatibility layer between python 2 and python 3. If msm still has future as dependency then MSM is not yet fully python 3 migrated.

Future does not have any effect on the python 3.6 as shown above. There most likely is not even a package for it, hence the "ModuleNotFoundError: No module named 'future'"

However not really sure where the "future" dependency comes from as setup.py from msn only states GitPython and Typing as requirements.

BTW; python-typing again has no effect on python3.6 as well.

**Comment by forslund** [comment]
As @penrods correctly recalls we removed the python2 support from msm which fixes this issue.

https://github.com/MycroftAI/mycroft-skills-manager/commit/23e2e5845710a3d307e7ece84cffe524f5579927

And is available in msm 0.5.19. Closing this issue.

**Comment by j1nx** [comment]
@forslund But it wasn't fixed in 0.5.17 and 0.5.18 and those versions are within requirements.txt at the last tagged 18.2.x release.

So if you download the last tagged 18.2 release of mycroft, this issue still remains.

**Comment by forslund** [comment]
But that shouldn't be an issue since the dev_setup script  or pip install of mycroft core installs future as a requirement. Which is why it worked when installed in the mycroft-core venv but installing standalone will trigger the error.

**Comment by j1nx** [comment]
hmmm ok, monkey business then as Python3 should not use future at all;
https://pypi.org/project/future/
Anyhow, if it works it works. case closed ;)
