### ISSUE TITLE
ERROR - Failed to fetch remote configuration: TypeError("'NoneType' object does not support item assignment",)

### ISSUE THREAD

**Issue by mathiasconradt** [MycroftAI/mycroft-core#1735]
I followed the instructions on https://github.com/MycroftAI/mycroft-core#getting-started and installed `mycroft-core` on a Ubuntu 18 VM. The VM does have an internet connection, no proxy in between. In fact, I am typing this github ticket from within the VM right now.

I ran a `./start-mycroft audiotest` and I was able to record my voice and hear it back afterwards. So audio seems to be fine in general.

I paired the mycroft with home.mycroft.ai and registered it as a device.

I start the service via `./start-mycroft.sh debug`

The mic level show a proper value.

First issue:
When I say something, I get this error in the log:

```
~~~~01.289 - mycroft.configuration.config:__init__:188 - ERROR - Failed to fetch remote configuration: TypeError("'NoneType' object does not support item assignment",)
Traceback (most recent call last):
File "/home/mconradt/mycroft-core/mycroft/configuration/config.py", line 173, in __init__
setting["location"] = location
TypeError: 'NoneType' object does not support item assignment
```
And I am not able to ask mycroft anything. Mycroft does not react to "Hey Mycroft" at all.

Another thing I noticed is: when I run the audioaccuracytest I get a warning that no wav files are found. Is that normal?

```
~/mycroft-core$ ./start-mycroft.sh audioaccuracytest
Initializing...
Starting audioaccuracytest
Warning: No wav files found in audio-accuracy-test/data/with_wake_word/query_after
Warning: No wav files found in audio-accuracy-test/data/without_wake_word
Complete!
```
In case it's helpful, this is the output of the audiotest, which seems to be successful, at least I can record something and hear it again. But I also notice the same error in the output that I got in the debug screen before:

```
~/mycroft-core$ ./start-mycroft.sh audiotest
/usr/lib/python3.6/runpy.py:125: RuntimeWarning: 'mycroft.util.audio_test' found in sys.modules after import of package 'mycroft.util', but prior to execution of 'mycroft.util.audio_test'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
 ===========================================================
 ==         STARTING TO RECORD, MAKE SOME NOISE!          ==
 ===========================================================
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib setup.c:547:(add_elem) Cannot obtain info for CTL elem (MIXER,'IEC958 Playback Default',0,0,0): No such file or directory
ALSA lib setup.c:547:(add_elem) Cannot obtain info for CTL elem (MIXER,'IEC958 Playback Default',0,0,0): No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
 ===========================================================
 ==           DONE RECORDING, PLAYING BACK...             ==
 ===========================================================
21:40:54.546 - mycroft.configuration.config:load_local:124 - DEBUG - Configuration /home/mconradt/mycroft-core/mycroft/configuration/mycroft.conf loaded
21:40:54.547 - mycroft.configuration.config:load_local:124 - DEBUG - Configuration /home/mconradt/mycroft-core/mycroft/configuration/mycroft.conf loaded
21:40:54.548 - mycroft.configuration.config:load_local:129 - DEBUG - Configuration '/etc/mycroft/mycroft.conf' not found
21:40:54.549 - mycroft.configuration.config:load_local:129 - DEBUG - Configuration '/home/mconradt/.mycroft/mycroft.conf' not found
21:40:54.555 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai:443
21:40:55.113 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/33ae5dbf-2b94-415f-847c-3717d74708d0 HTTP/1.1" 200 364
21:40:55.122 - mycroft.api:send:115 - DEBUG - Updating etag for: device/33ae5dbf-2b94-415f-847c-3717d74708d0
21:40:55.137 - mycroft.configuration.config:load_local:124 - DEBUG - Configuration /home/mconradt/mycroft-core/mycroft/configuration/mycroft.conf loaded
21:40:55.146 - mycroft.configuration.config:load_local:129 - DEBUG - Configuration '/etc/mycroft/mycroft.conf' not found
21:40:55.150 - mycroft.configuration.config:load_local:129 - DEBUG - Configuration '/home/mconradt/.mycroft/mycroft.conf' not found
21:40:55.155 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai:443
21:40:55.757 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/33ae5dbf-2b94-415f-847c-3717d74708d0/setting HTTP/1.1" 200 4
21:40:55.771 - mycroft.api:send:115 - DEBUG - Updating etag for: device/33ae5dbf-2b94-415f-847c-3717d74708d0/setting
21:40:55.774 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai:443
21:40:56.300 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/33ae5dbf-2b94-415f-847c-3717d74708d0/location HTTP/1.1" 200 888
21:40:56.306 - mycroft.api:send:115 - DEBUG - Updating etag for: device/33ae5dbf-2b94-415f-847c-3717d74708d0/location
21:40:56.309 - mycroft.configuration.config:__init__:188 - ERROR - Failed to fetch remote configuration: TypeError("'NoneType' object does not support item assignment",)
Traceback (most recent call last):
  File "/home/mconradt/mycroft-core/mycroft/configuration/config.py", line 173, in __init__
    setting["location"] = location
TypeError: 'NoneType' object does not support item assignment
21:40:56.320 - mycroft.configuration.config:load_local:129 - DEBUG - Configuration '/var/tmp/mycroft_web_cache.json' not found
21:40:56.323 - mycroft.configuration.config:load_local:129 - DEBUG - Configuration '/etc/mycroft/mycroft.conf' not found
21:40:56.324 - mycroft.configuration.config:load_local:129 - DEBUG - Configuration '/home/mconradt/.mycroft/mycroft.conf' not found
```

**Comment by mathiasconradt** [comment]
Might it eventually be possible that the remote configuration cannot be loaded because I am not able to save my settings on home.mycroft.ai, see the other issue I submitted: https://github.com/MycroftAI/mycroft-core/issues/1736 ?

**Comment by MatthewScholefield** [comment]
Audio accuracy test is an automated test of the wake word system, unrelated to whether the microphone works. It's used to simulate a series of wake words being spoken to verify the system works appropriately. As for the main issue, it does indeed look like there's some sort of bug there, but I'm not sure if it's related to the other issue.

**Comment by mathiasconradt** [comment]
Turns out that this issue was cause by my specific user account obviously being corrupt (database inconcistency), see https://github.com/MycroftAI/mycroft-core/issues/1736 
I created a new mycroft account and everything works fine. So I am closing this ticket.
