### ISSUE TITLE
Traceback when running source build based on Python 3.4

### ISSUE THREAD

**Issue by ndarilek** [MycroftAI/mycroft-core#1749]
I switched away from the Debian package to a source build, but unfortunately this isn't working for me under Python 3.4/Debian Jessie, which I understood was the primary supported OS base and Python version. Looks like a syntax error in future, maybe it's using newer Python?:

```
Traceback (most recent call last):
  File "/usr/local/bin/mycroft-messagebus", line 9, in <module>
    load_entry_point('mycroft-core==18.2.12', 'console_scripts', 'mycroft-messagebus')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/mycroft_core-18.2.12-py3.4.egg/mycroft/messagebus/service/main.py", line 15, in <module>
    from tornado import autoreload, web, ioloop
  File "/usr/local/lib/python3.4/dist-packages/tornado-4.2.1-py3.4-linux-armv6l.egg/tornado/autoreload.py", line 93, in <module>
    from tornado import ioloop
  File "/usr/local/lib/python3.4/dist-packages/tornado-4.2.1-py3.4-linux-armv6l.egg/tornado/ioloop.py", line 46, in <module>
    from tornado.concurrent import TracebackFuture, is_future
  File "/usr/local/lib/python3.4/dist-packages/tornado-4.2.1-py3.4-linux-armv6l.egg/tornado/concurrent.py", line 37, in <module>
    from concurrent import futures
  File "/usr/local/lib/python3.4/dist-packages/futures-3.0.3-py3.4.egg/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/local/lib/python3.4/dist-packages/futures-3.0.3-py3.4.egg/concurrent/futures/_base.py", line 355
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax
2018-08-16 15:54:33,526 INFO exited: messagebus (exit status 1; not expected)
2018-08-16 15:54:34,536 INFO spawned: 'messagebus' with pid 380
2018-08-16 15:54:35,542 INFO success: messagebus entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/usr/local/bin/mycroft-audio", line 9, in <module>
    load_entry_point('mycroft-core==18.2.12', 'console_scripts', 'mycroft-audio')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/mycroft_core-18.2.12-py3.4.egg/mycroft/audio/main.py", line 28, in <module>
    import mycroft.audio.speech as speech
  File "/usr/local/lib/python3.4/dist-packages/mycroft_core-18.2.12-py3.4.egg/mycroft/audio/speech.py", line 21, in <module>
    from mycroft.tts import TTSFactory
  File "/usr/local/lib/python3.4/dist-packages/mycroft_core-18.2.12-py3.4.egg/mycroft/tts/__init__.py", line 430, in <module>
    class TTSFactory(object):
  File "/usr/local/lib/python3.4/dist-packages/mycroft_core-18.2.12-py3.4.egg/mycroft/tts/__init__.py", line 432, in TTSFactory
    from mycroft.tts.fa_tts import FATTS
  File "/usr/local/lib/python3.4/dist-packages/mycroft_core-18.2.12-py3.4.egg/mycroft/tts/fa_tts.py", line 18, in <module>
    from mycroft.tts.remote_tts import RemoteTTS
  File "/usr/local/lib/python3.4/dist-packages/mycroft_core-18.2.12-py3.4.egg/mycroft/tts/remote_tts.py", line 17, in <module>
    from requests_futures.sessions import FuturesSession
  File "/usr/local/lib/python3.4/dist-packages/requests_futures-0.9.5-py3.4.egg/requests_futures/sessions.py", line 23, in <module>
    from concurrent.futures import ThreadPoolExecutor
  File "/usr/local/lib/python3.4/dist-packages/futures-3.0.3-py3.4.egg/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/local/lib/python3.4/dist-packages/futures-3.0.3-py3.4.egg/concurrent/futures/_base.py", line 355
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax
2018-08-16 15:54:39,942 INFO exited: audio (exit status 1; not expected)
```

This is with the release/v18.2.12 tag, I was attempting to pin a stable version for my image.

Thanks.

**Comment by forslund** [comment]
This seems to be a weird one, I've been googling around a bit and it seem to be a tricky issue to reproduce. A Possible/probable issue is the requirement futures==3.0.3, according to the [README](https://github.com/agronholm/pythonfutures) it shouldn't be used with python3.

Can you try to remove the line from requirements.txt and see if that resolves the issue? If it does I'm not sure how it's ever been working on any install ever.

**Comment by ndarilek** [comment]
Haven't tried removing the dependency yet, but I'm wondering if this is 
tangentially related. I've just been running `python3 setup.py install` 
and assuming that would install all needed dependencies. Interestingly 
enough, when I do that I get:

```
Searching for SpeechRecognition==3.8.1
Reading https://pypi.python.org/simple/SpeechRecognition/
No local packages or download links found for SpeechRecognition==3.8.1
error: Could not find suitable distribution for 
Requirement.parse('SpeechRecognition==3.8.1')
```

So I've been separately installing SpeechRecognition to work around this.

If I first do `pip3 install -r requirements.txt`, this step works fine. 
Likewise, if I `pip3 install SpeechRecognition` before running this 
step, everything works fine.

So it could be that I don't know enough about Python dependency 
management to do this correctly, but it looks like setup.py *should* 
automatically install requirements.txt. If it doesn't, then 
SpeechRecognition is an odd hill for it to pick to die on. :) I don't 
know why setup.py installs some requirements and not everything.

Here's a Dockerfile that gets me to the point where I can experiment 
with this:

```
FROM debian:jessie
ENV HOME /config/mycroft
ENV VERSION 18.2.13
RUN apt-get update && apt-get install -y jq git python3-dev 
python3-setuptools swig build-essential libfann-dev libz-dev libjpeg-dev 
linux-libc-dev libasound2-dev portaudio19-dev alsa-utils supervisor 
virtualenv libpulse-dev mpg123 pulseaudio-utils vorbis-tools python3-pip 
espeak
RUN pip3 install --upgrade pip pyasn1
RUN git clone https://github.com/mycroftai/mycroft-core
WORKDIR /mycroft-core
RUN git checkout release/v$VERSION
# pip3 install -r requirements.txt # Not initially present, Installation 
finishes if uncommented.
# RUN python3 setup.py install # Seems to partially install 
requirements, chooses not to find SpeechRecognition
```

So maybe things will work if I first explicitly install 
requirements.txt, but I'd be curious to know why some requirements 
install fine and SpeechRecognition isn't found.

I'm going to try installing requirements separately to see if that makes 
the error go away. Maybe there's a version check in `pip3 install -r 
requirements.txt which isn't getting triggered in setup.py for some reason.

**Comment by forslund** [comment]
I created a new virtualenv and ran python setup.py install

and got this output
```
Processing dependencies for mycroft-core==18.2.13
Searching for SpeechRecognition==3.8.1
Reading https://pypi.org/simple/SpeechRecognition/
Downloading https://files.pythonhosted.org/packages/26/e1/7f5678cd94ec1234269d23756dbdaa4c8cfaed973412f88ae8adf7893a50/SpeechRecognition-3.8.1-py2.py3-none-any.whl#sha256=4d8f73a0c05ec70331c3bacaa89ecc06dfa8d9aba0899276664cda06ab597e8e
Best match: SpeechRecognition 3.8.1
Processing SpeechRecognition-3.8.1-py2.py3-none-any.whl
Installing SpeechRecognition-3.8.1-py2.py3-none-any.whl to /home/ake/.virtualenvs/setup-test/lib/python3.6/site-packages
Adding SpeechRecognition 3.8.1 to easy-install.pth file
```

So it should as far as I know install the requirements (but I am in no way an expert here either).

**Comment by ndarilek** [comment]
What version of Python?

**Comment by forslund** [comment]
That was 3.6, I'll re-run it using python3.4. One moment

**Comment by ndarilek** [comment]
Also, FWIW, I'm not in a virtualenv. Not sure what difference that 
makes, but something here is behaving nondeterministically and I can't 
figure out what's causing it.

**Comment by ndarilek** [comment]
Installing the requirements in a separate step seems to make this work. 
Maybe there's a difference between how setuptools and the latest version 
of pip install/resolve their dependencies?

**Comment by forslund** [comment]
Maybe, I get the same thing when I try on python 3.4. Odd

**Comment by forslund** [comment]
Using pip to install it seems to work as well.

```
pip3 install path/to/mycroft-core
```

**Comment by ndarilek** [comment]
Now I get a similar traceback, but for libtiff.so.5.

When I look at the build logs, I don't see any native dependencies being 
built when I just do `pip3 install -r requirements.txt && python3 
setup.py install`. So these steps aren't equivalent in a few key ways.

It would be nice if there was only one way to get this done, and if that 
way complained loudly if your environment wasn't missing a critical 
shared library or something else that might silently make things fail. :)

**Comment by j1nx** [comment]
'pip install" will try to download binary wheels if present, otherwise defaults to source packages.

'setup.py install' utilizing python setuptools will always build from source packages. However for instance with 'SpeechRecognition 3.8.1' there are no source code tarballs released. (https://pypi.org/project/SpeechRecognition/#files) and will therefor fail.

You can alter the pip install command with the " --no-binary :all: " command parameter and you will see it will fail on finding a package for speechrecognition as well.

pip install --no-binary :all: -r requirements.txt

(figured that out while trying to create a buildroot package for mycroft)

**Comment by domcross** [comment]
As support for Python 3.4 is dropped now: can this issue be closed?

**Comment by forslund** [comment]
Yes I think so. @ndarilek if you still see the issue feel free to reopen.
