### ISSUE TITLE
Upgrade to 18.8.2 fails to upgrade Python package requests from 2.13.0 to 2.19.1

### ISSUE THREAD

**Issue by kjcole** [MycroftAI/mycroft-core#1823]
This morning `apt full-upgrade` installed the latest and greatest `mycroft-core` and `mycroft-mark1` (18.8.2) on my Mark 1.

After I manually rebooted (`sudo shutdown -r now`) it wasn't responding to "Hey, Mycroft!" So, I tried the `mycroft-cli-client` and got:

```
$ mycroft-cli-client 
Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.13.0 (/opt/venvs/mycroft-core/lib/python3.4/site-packages), Requirement.parse('requests==2.19.1'), {'mycroft-core'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/bin/mycroft-cli-client", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3112, in <module>
    @_call_aside
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3096, in _call_aside
    f(*args, **kwargs)
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3125, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pkg_resources/__init__.py", line 580, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pkg_resources/__init__.py", line 593, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests==2.19.1' distribution was not found and is required by mycroft-core
$
```

**Comment by forslund** [comment]
Hi, do you know what the previous version was?

**Comment by forslund** [comment]
We added a step that reinstalls skills requirements and if you have a skill with a fixed older version it could cause this issue (we had it ourself with skill weather at one point)

You can try to run
`sudo mycroft-pip install --upgrade requests==2.19.1`

**Comment by kjcole** [comment]
forslund wrote:

> Hi, do you know what the previous version was? (requests==2.19.1 has been the requests version used for quite some time).

Previous version of mycroft-core? Not sure. I want to say 18.8.1 since I do an `apt full-upgrade` quite often. And as of two days ago `msm update` said there were no skills updates, and `mycroft-cli-client` worked fine.

> You can try to run
> sudo mycroft-pip install --upgrade requests==2.19.1

That and a reboot appeared to fix things. 

Without the reboot, `mycroft-cli-client` messed up: ncurses -- or similar -- started "stair-stepping" error messages all over the screen (mimicking old-school LF without CR), with most errors relating to some connection failure.

**Comment by forslund** [comment]
Ah yes, that happens when the services aren't running. Forgot to mention that.

That you had a recent mycroft makes me believe it was a skill that downgraded your requests. It would be interesting if you could check the installed skills for a `requests==2.13.0` line.

mycroft-weather or skill-mopidy may be good places to start

**Comment by forslund** [comment]
Another candidate may be may have been the old `skill-wolfram-alpha` now replaced by `fallback-wolfram-alpha`
