### ISSUE TITLE
I have a Question about Skills that are not in your repository

### ISSUE THREAD

**Issue by Z3r0ut** [MycroftAI/mycroft-core#2247]
I have found a skills list here: https://andlo.github.io/mycroft-skills-list/
but the skills i wanted (Youtube, Internet radio, autogui and some others)
Doesnt work. They show up when i type "Skills list" in the debug menu, but they are marked red instead of yelllow.
and for the Internet radio i need https://account.mycroft.ai/skills but it doesnt show up there.

Does anyone know how to install these skills?
Edit: For example: mycroft.skills.core:load_skill:169 - ERROR - Failed to load skill: skill-internet-radio
                              mycroft.skills.core:load_skill:169 - ERROR - Failed to load skill: mycroft-youtube

**Comment by el-tocino** [comment]
There's usually some additional logging after the initial failed message explaining why they failed to load.  Review that and it should give you some pointers.

**Comment by Z3r0ut** [comment]
Ok, for example here the Autogui log (this is what happened after i have done git clone in the skills folder

`22:29:28.284 - mycroft.skills.core:load_skill:122 - INFO - ATTEMPTING TO LOAD SKILL: skill-autogui with ID skill-autogui
22:29:28.285 - mycroft.skills.core:load_skill:169 - ERROR - Failed to load skill: skill-autogui
Traceback (most recent call last):
  File "/home/z3r0ut/mycroft-core/mycroft/skills/core.py", line 131, in load_skill
    imp.PY_SOURCE))
  File "/usr/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/mycroft/skills/skill-autogui/__init__.py", line 94
    self.speak_dialog("typing")
                              ^
TabError: inconsistent use of tabs and spaces in indentation
`

**Comment by el-tocino** [comment]
Might want to fix the tabs and spaces and then it should reload after you edit it.

**Comment by Z3r0ut** [comment]
Im not an programmer. i dont know where a space to much is.

**Comment by el-tocino** [comment]
Contact the skill author, or check out pylint or something similar.

**Comment by Z3r0ut** [comment]
I have opened an Issue, although i dont have much hope there will be an answer.
And this Pylint gives me the same output as the Mycroft ai
not really helpfull in my case.
