### ISSUE TITLE
extract_datetime_es() failing on June, July and September

### ISSUE THREAD

**Issue by ChanceNCounter** [MycroftAI/mycroft-core#2348]
Though it seems to work on other months, `util.lang.parse_es.extract_datetime_es()` is failing on the aforementioned months in the following ways:

```
>>> extract_datetime_es("11 jun")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chance/development-mycroft-core/mycroft/util/lang/parse_es.py", line 1092, in extract_datetime_es
    temp = datetime.strptime(datestr, "%B %d")
  File "/usr/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data 'junee 11' does not match format '%B %d'
```
and the same for july - `jul` --> `julyy` - and `sep` --> `septtember`.

The same thing happens for the full name of each month, i.e. `extract_datetime_es("11 junio")`

**Comment by ChanceNCounter** [comment]
PR #2356 does _not_ fix any of these issues, but it _does_ modify these files, so anybody else who might touch these bugs might note whether it's been merged.

**Comment by ChanceNCounter** [comment]
Request move to Lingua Franca

**Comment by forslund** [comment]
Request granted!
