### ISSUE TITLE
Error during paring

### ISSUE THREAD

**Issue by weathon** [MycroftAI/mycroft-core#2363]
After I pair, it gives me this error
```bash
 21:01:28.914 | ERROR    |  5174 | mycroft.skills.settings:_issue_api_call:310 | Failed to upload skill settings meta for mycroft-pairing|19.08
Traceback (most recent call last):
  File "/root/mycroft-core/mycroft/skills/settings.py", line 307, in _issue_api_call
    self.api.upload_skill_metadata(self.settings_meta)
  File "/root/mycroft-core/mycroft/api/__init__.py", line 382, in upload_skill_metadata
    "json": settings_meta
  File "/root/mycroft-core/mycroft/api/__init__.py", line 69, in request
    return self.send(params)
  File "/root/mycroft-core/mycroft/api/__init__.py", line 152, in send
    return self.get_response(response, no_refresh)
  File "/root/mycroft-core/mycroft/api/__init__.py", line 174, in get_response
    raise HTTPError(data, response=response)
requests.exceptions.HTTPError: {'skill_gid': ['Received skill setting definition before manifest for skill mycroft-pairing|19.08']}
~~~~4 | mycroft.skills.settings:_update_settings_meta:301 | DEPRECATION WARNING: The "name" attribute in the settingsmeta file is no longer supported.
```

I am running  ```mycroft-core 19.8.1``` on my Linux raspberry pi 1 B+ (I didn't install the PiCroft but install as normal Linux)

**Comment by weathon** [comment]
also have this 
```~~~~="width:360px;">\n  </div>\n</div>\n\n  <div aria-live="polite" class="js-global-screen-reader-notice sr-only"></div>\n\n  </body>\n</html>.md5'))
~~~~="width:360px;">\n  </div>\n</div>\n\n  <div aria-live="polite" class="js-global-screen-reader-notice sr-only"></div>\n\n  </body>\n</html>.md5'))
 21:06:17.298 | WARNING  |  5174 | mycroft.skills.fallback_skill:handler:86 | No fallback could handle intent.
 21:06:18.516 | INFO     |  5180 | __main__:handle_complete_intent_failure:85 | Failed to find intent.
```

**Comment by forslund** [comment]
Hi, that may occur right after pairing, basically the backend tells core that it can't accept settings yet. It shouldn't be critical to the pairing process.

Is there any other symptoms of issues?

**Comment by weathon** [comment]
This happened so many times and sometimes it has a timeout error

**Comment by weathon** [comment]
```
 06:24:32.244 | INFO     | 17929 | PairingSkill | Pairing code: PNJRW4
 06:25:43.898 | INFO     | 17929 | PairingSkill | Pairing code: PNJRW4
~~~~ld not get device info: ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='api.mycroft.ai', port=443): Read timed out. (read timeout=3.05)"))
 06:26:46.324 | INFO     | 17929 | PairingSkill | Restarting pairing process
~~~~eoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x9fb95270>, 'Connection to api.mycroft.ai timed out. (connect timeout=3.05)'))"))
~~~~eoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x9fb8ead0>, 'Connection to api.mycroft.ai timed out. (connect timeout=3.05)'))"))
 06:27:13.195 | INFO     | 17929 | PairingSkill | Pairing code: 7CR9UL
 06:28:24.795 | INFO     | 17929 | PairingSkill | Pairing code: 7CR9UL
 06:29:36.702 | INFO     | 17929 | PairingSkill | Pairing code: 7CR9UL
 06:30:49.939 | INFO     | 17929 | PairingSkill | Pairing code: 7CR9UL
```

**Comment by forslund** [comment]
Hi @weathon did you manage to get pairing working or are you still having this issue?

**Comment by weathon** [comment]
No, it works well now. Thanks
