### ISSUE TITLE
Typing only required for Python <3.5

### ISSUE THREAD

**Issue by j1nx** [MycroftAI/mycroft-core#2419]
After I upgraded my system for Python 3.8 I ran into the following error when I tried to run "mycroft-cli-client"

`Traceback (most recent call last):
  File "/bin/mycroft-cli-client", line 11, in <module>
    load_entry_point('mycroft-core==19.8.4', 'console_scripts', 'mycroft-cli-client')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/mycroft/__init__.py", line 18, in <module>
    from mycroft.messagebus.message import Message
  File "/usr/lib/python3.8/site-packages/mycroft/messagebus/__init__.py", line 14, in <module>
    from .client.client import MessageBusClient
  File "/usr/lib/python3.8/site-packages/mycroft/messagebus/client/__init__.py", line 14, in <module>
    from .client import MessageBusClient
  File "/usr/lib/python3.8/site-packages/mycroft/messagebus/client/client.py", line 30, in <module>
    from .threaded_event_emitter import ThreadedEventEmitter
  File "/usr/lib/python3.8/site-packages/mycroft/messagebus/client/threaded_event_emitter.py", line 15, in <module>
    from pyee import EventEmitter
  File "/usr/lib/python3.8/site-packages/pyee/__init__.py", line 30, in <module>
    from asyncio import iscoroutine, ensure_future
  File "/usr/lib/python3.8/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/lib/python3.8/asyncio/base_events.py", line 45, in <module>
    from . import staggered
  File "/usr/lib/python3.8/asyncio/staggered.py", line 6, in <module>
    import typing
  File "/usr/lib/python3.8/site-packages/typing.py", line 1357, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/usr/lib/python3.8/site-packages/typing.py", line 1005, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'`

Googling for it showed that typing is only requered for Python < 3.5 however MSM and MSK still have it as dependency.

Solved it by patching MSM and MSK to only depend on typing if Python version < 3.5

https://github.com/j1nx/MycroftOS/blob/1adee13f9fe808c36fdc5551ef32c5c01f6eb219/buildroot-external/package/python-msk/0001-Only-install-typing-requirement-if-Python-version-3..patch

https://github.com/j1nx/MycroftOS/blob/1adee13f9fe808c36fdc5551ef32c5c01f6eb219/buildroot-external/package/python-msm/0002-Only-install-typing-if-Python-version-3.5.patch

MSM also needs a patch for requirements.txt by;

`typing; python_version < '3.5'`

Not included in above patches as Buildroot handles the requirements.txt differently.

Anyhow, is above something that fits into mycroft standards? If so, I am more than happy to create PR's for above packages at their respective repositories.

**Comment by ChanceNCounter** [comment]
3.4 was dropped in 19.8.3, since it's EOL. Reckon that means the dependency can just be nuked, no?

**Comment by j1nx** [comment]
Ah shoot. Indeed you are right. 

Does that also count for all other parts? Guess so...

**Comment by forslund** [comment]
Thanks for reporting this, We'll get typing removed as a dependency for the next release of msk and msm.

In Msm the update has [been merged](https://github.com/MycroftAI/mycroft-skills-manager/pull/59)

**Comment by j1nx** [comment]
Allright then we can close this already.

Funny that Python 3.8 gives an error, while 3.7 still worked..
