### ISSUE TITLE
Connection refused on first startup.

### ISSUE THREAD

**Issue by DAMO238** [MycroftAI/mycroft-core#2486]
## Issue

I am trying to setup mycroft on Arch. dev_setup.py works perfectly and then I run ./start_mycroft.sh debug and I get the following error (formatting is horrible for some reason)

```
File "/home/damien/mycroft-core/mycroft/messagebus/client/client.py", line 84, in on_error
                                                                                                                 self.emitter.emit('error', error)
                                                                                                                                                    File "/home/damien/mycroft-core/.venv/lib/python3.8/site-packages/pyee/__init__.py", line 178, in emit
                                                                                                  raise args[0]
                                                                                                                 File "/home/damien/mycroft-core/.venv/lib/python3.8/site-packages/websocket/_app.py", line 248, in run_forever
                                                                       self.sock.connect(
                                                                                           File "/home/damien/mycroft-core/.venv/lib/python3.8/site-packages/websocket/_core.py", line 219, in connect
                                              self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
                                                                                                                     File "/home/damien/mycroft-core/.venv/lib/python3.8/site-packages/websocket/_http.py", line 120, in connect
                                                                        sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
                                                                                                                                              File "/home/damien/mycroft-core/.venv/lib/python3.8/site-packages/websocket/_http.py", line 190, in _open_socket
                                                                                                      raise err
                                                                                                                 File "/home/damien/mycroft-core/.venv/lib/python3.8/site-packages/websocket/_http.py", line 170, in _open_socket
                                                                         sock.connect(address)
                                                                                              ConnectionRefusedError: [Errno 111] Connection refused

                                                                                                                                                    During handling of the above exception, another exception occurred:

                                                           Traceback (most recent call last):
                                                                                               File "/home/damien/mycroft-core/mycroft/messagebus/client/client.py", line 84, in on_error
                                 self.emitter.emit('error', error)
                                                                    File "/home/damien/mycroft-core/.venv/lib/python3.8/site-packages/pyee/__init__.py", line 178, in emit
                  raise args[0]
                                 File "/home/damien/mycroft-core/.venv/lib/python3.8/site-packages/websocket/_app.py", line 248, in run_forever
                                                                                                                                                   self.sock.connect(
           File "/home/damien/mycroft-core/.venv/lib/python3.8/site-packages/websocket/_core.py", line 219, in connect
                                                                                                                          self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
                                     File "/home/damien/mycroft-core/.venv/lib/python3.8/site-packages/websocket/_http.py", line 120, in connect
                                                                                                                                                    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
                                                              File "/home/damien/mycroft-core/.venv/lib/python3.8/site-packages/websocket/_http.py", line 190, in _open_socket
                      raise err
                                 File "/home/damien/mycroft-core/.venv/lib/python3.8/site-packages/websocket/_http.py", line 170, in _open_socket
                                                                                                                                                     sock.connect(address)
              ConnectionRefusedError: [Errno 111] Connection refused

                                                                    During handling of the above exception, another exception occurred:

                                                                                                                                       Traceback (most recent call last):
               File "/home/damien/mycroft-core/.venv/lib/python3.8/site-packages/websocket/_app.py", line 248, in run_forever
                                                                                                                                 self.sock.connect(
                                                                                                                                                     File "/home/damien/mycroft-core/.venv/lib/python3.8/site-packages/websocket/_core.py", line 219, in connect
                                                                                                        self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
                   File "/home/damien/mycroft-core/.venv/lib/python3.8/site-packages/websocket/_http.py", line 120, in connect
                                                                                                                                  sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
                                            File "/home/damien/mycroft-core/.venv/lib/python3.8/site-packages/websocket/_http.py", line 190, in _open_socket
    raise err
               File "/home/damien/mycroft-core/.venv/lib/python3.8/site-packages/websocket/_http.py", line 170, in _open_socket
                                                                                                                                   sock.connect(address)
                                                                                                                                                        ConnectionRefusedError: [Errno 111] Connection refused
                                                  2020-02-28 17:23:21.208 | ERROR    | 126813 | mycroft.messagebus.client.client:on_error:88 | Exception closing websocket: ConnectionRefusedError(111, 'Connection refused')
                                                                 2020-02-28 17:23:21.218 | WARNING  | 126813 | mycroft.messagebus.client.client:on_error:90 | Message Bus Client will reconnect in 60 seconds.

```
## To reproduce

git clone into a new folder in $HOME, cd in, bash dev_setup.sh, ./start_mycroft.py debug

## Screenshot

[https://imgur.com/a/NSy4AK6](url)

**Comment by krisgesling** [comment]
The connection refused error is saying that it cannot connect to the Mycroft MessageBus which is a websocket on port 8181.

I'd be interested to first see if stopping and starting Mycroft has any effect:
```
./stop-mycroft.sh
./start-mycroft.sh debug
```

When starting Mycroft you should get an output like this before the CLI displays:
```
Starting all mycroft-core services
Initializing...
Starting background service bus
CAUTION: The Mycroft bus is an open websocket with no built-in security
         measures.  You are responsible for protecting the local port
         8181 with a firewall as appropriate.
Starting background service skills
Starting background service audio
Starting background service voice
Starting cli
```

After you've started Mycroft can you see the mycroft.messagebus.service processes running?

**Comment by DAMO238** [comment]
Even though I already tried stopping all services and starting again, it just fixed itself this time... Wierd. Thanks for all the help!

**Comment by krisgesling** [comment]
Yeah there's definitely something going on that we're trying to nail down but it's quite sporadic and unpredictable. Glad it's working now though.
