### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by PureTryOut** [MycroftAI/mycroft-core#2580]
I'm running Mycroft on Alpine Linux using system packages (so the latest of everything) and Python 3.8. Mycroft works fine for a while, but after some unknown amount of time it either crashes with the below error or I can not restart because of it.

I'm not sure what directory it's trying to access, but it seems it's something related to Git?

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/git/__init__.py", line 83, in <module>
    refresh()
  File "/usr/lib/python3.8/site-packages/git/__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "/usr/lib/python3.8/site-packages/git/cmd.py", line 215, in refresh
    cls().version()
  File "/usr/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/lib/python3.8/site-packages/git/cmd.py", line 686, in execute
    cwd = self._working_dir or os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mycroft-skills", line 11, in <module>
    load_entry_point('mycroft-core==20.2.3', 'console_scripts', 'mycroft-skills')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/mycroft/__init__.py", line 19, in <module>
    from mycroft.skills.context import adds_context, removes_context
  File "/usr/lib/python3.8/site-packages/mycroft/skills/__init__.py", line 21, in <module>
    from .mycroft_skill import (MycroftSkill, intent_handler, intent_file_handler,
  File "/usr/lib/python3.8/site-packages/mycroft/skills/mycroft_skill/__init__.py", line 15, in <module>
    from .mycroft_skill import MycroftSkill
  File "/usr/lib/python3.8/site-packages/mycroft/skills/mycroft_skill/mycroft_skill.py", line 53, in <module>
    from ..settings import get_local_settings, save_settings
  File "/usr/lib/python3.8/site-packages/mycroft/skills/settings.py", line 69, in <module>
    from .msm_wrapper import build_msm_config, create_msm
  File "/usr/lib/python3.8/site-packages/mycroft/skills/msm_wrapper.py", line 26, in <module>
    from msm import MycroftSkillsManager, SkillRepo
  File "/usr/lib/python3.8/site-packages/msm/__init__.py", line 22, in <module>
    from .exceptions import *
  File "/usr/lib/python3.8/site-packages/msm/exceptions.py", line 24, in <module>
    from git import GitError
  File "/usr/lib/python3.8/site-packages/git/__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: [Errno 2] No such file or directory
```

**Comment by PureTryOut** [comment]
Ah never mind, I found the problem. This happens when you're in a directory that has been deleted from somewhere else, and then launch any of the Mycroft components. It doesn't seem like that is something that requires fixing.
