### ISSUE TITLE
OSError Invalid cross-device link on Arch Linux

### ISSUE THREAD

**Issue by rolandg** [MycroftAI/mycroft-core#2624]
## Be clear about the software, hardware and version you are running
running on latest Arch Linux using mycroft-core package

## Try to provide steps that we can use to replicate the Issue
1. Start mycroft
2. observe log

## Provide log files or other output to help us see the error

```
2020-06-24 00:13:42.995 | INFO     | 718340 | msm.skill_entry | Problem performing action. Restoring skill to previous state...
2020-06-24 00:13:42.995 | INFO     | 718340 | msm.mycroft_skills_manager | invalidating skills cache
2020-06-24 00:13:42.996 | WARNING  | 718340 | mycroft.skills.skill_updater:install_or_update:215 | Failed to install default skill: mycroft-singing
2020-06-24 00:13:42.997 | ERROR    | 718340 | msm.mycroft_skills_manager | Error running install_or_update on mycroft-singing:
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 788, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpjldoa4wy' -> '/opt/mycroft/skills/mycroft-singing.mycroftai'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/mycroft-core/.venv/lib/python3.8/site-packages/msm/mycroft_skills_manager.py", line 461, in run_item
    func(skill)
  File "/usr/share/mycroft-core/mycroft/skills/skill_updater.py", line 212, in install_or_update
    self.msm.install(skill, origin='default')
  File "/usr/share/mycroft-core/.venv/lib/python3.8/site-packages/msm/mycroft_skills_manager.py", line 73, in func_wrapper
    ret = func(self, *args, **kwargs)
  File "/usr/share/mycroft-core/.venv/lib/python3.8/site-packages/msm/mycroft_skills_manager.py", line 376, in install
    skill.install(constraints)
  File "/usr/share/mycroft-core/.venv/lib/python3.8/site-packages/msm/skill_entry.py", line 82, in wrapper
    func(self, *args, **kwargs)
  File "/usr/share/mycroft-core/.venv/lib/python3.8/site-packages/msm/skill_entry.py", line 473, in install
    move(tmp_location, self.path)
  File "/usr/lib/python3.8/shutil.py", line 798, in move
    copytree(src, real_dst, copy_function=copy_function,
  File "/usr/lib/python3.8/shutil.py", line 554, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib/python3.8/shutil.py", line 455, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/opt/mycroft/skills/mycroft-singing.mycroftai'
```

**Comment by forslund** [comment]
Hi,

is this installed using the arch package manager or is it installed from this git repo using the `dev_setup.sh`?

It looks like your user don't have permission to create the skill directory. Does the /opt/mycroft/skills folder exist?

**Comment by rolandg** [comment]
Hi,
I'm using this AUR package: https://aur.archlinux.org/packages/mycroft-core/

> Does the /opt/mycroft/skills folder exist?
```
[I] ➜ sudo ls /opt/mycroft/skills -la
total 8
drwxr-xr-x 2 root    root    4096 Jun 23 22:03 .
drwxr-xr-x 4 mycroft mycroft 4096 Jun 23 22:05 ..
```
yes

**Comment by krisgesling** [comment]
Hi Roland it looks like your `/opt/mycroft/skills` is owned by root, try changing that owner to mycroft:
```
cd /opt/mycroft/
sudo chown mycroft:mycroft skills
```

**Comment by rolandg** [comment]
that resolved the issue. might have started it as root first. thanks
