### ISSUE TITLE
Unable to connect to messagebus

### ISSUE THREAD

**Issue by Xanaxus** [MycroftAI/mycroft-core#2726]
Hey  pretty new to this using it on my Linux laptop (popOs), 
![image](https://user-images.githubusercontent.com/53279068/92256644-973b5b00-eef1-11ea-92ff-a8d83c84c819.png)

![image](https://user-images.githubusercontent.com/53279068/92259798-fc448000-eef4-11ea-926f-551bd9e52188.png)

and it doesn't speak back when I type in CLI 

Soory if this has been explained in the trouble shooting page but I have tried the audio fix and wake fix but no use

worked well on the first day but not on the subsequent  days

**Comment by krisgesling** [comment]
Hey I've transferred this to mycroft-core as it's an audio issue.

I'd be investigating these two error messages:
```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/ivanpereira/mycroft-core/mycroft/client/speech/listener.py", line 79, in run
    with self.mic as source:
  File "/home/ivanpereira/mycroft-core/mycroft/client/speech/mic.py", line 140, in __enter__
    return self._start()
  File "/home/ivanpereira/mycroft-core/mycroft/client/speech/mic.py", line 147, in _start
    self.stream = MutableStream(self.audio.open(
  File "/home/ivanpereira/mycroft-core/.venv/lib/python3.8/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/home/ivanpereira/mycroft-core/.venv/lib/python3.8/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9996] Invalid input device (no default output device)
```

```
2020-09-07 10:39:38.008 | INFO     | 12485 | __main__:on_ready:175 | Speech client is ready.
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/ivanpereira/mycroft-core/mycroft/client/speech/listener.py", line 79, in run
    with self.mic as source:
  File "/home/ivanpereira/mycroft-core/mycroft/client/speech/mic.py", line 140, in __enter__
    return self._start()
  File "/home/ivanpereira/mycroft-core/mycroft/client/speech/mic.py", line 147, in _start
    self.stream = MutableStream(self.audio.open(
  File "/home/ivanpereira/mycroft-core/.venv/lib/python3.8/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/home/ivanpereira/mycroft-core/.venv/lib/python3.8/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9997] Invalid sample rate
```

**Comment by forslund** [comment]
Could you provide some details of how you start mycroft and the platform. You mention that it's at boot. Could it be something related to the pulseaudio session?

**Comment by CodingPenguin1** [comment]
I am also having this issue. @Xanaxus what skill did you install? I'd like to try to get to the same point you are

**Comment by Xanaxus** [comment]
> Could you provide some details of how you start Mycroft. You mention that it's at boot? systemd script or during login to desktop? Could it be something related to the pulseaudio session?

Its a systemd script :- [https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/get-mycroft/linux#start-mycroft-on-boot](url)

**Comment by CodingPenguin1** [comment]
@Xanaxus are you using Anaconda? I was able to solve this issue by disabling my conda environment, then starting Mycroft

**Comment by krisgesling** [comment]
I'd also take a look at the work j1nx has been doing around using systemd to start Mycroft:
https://github.com/j1nx/mycroft-systemd

**Comment by krisgesling** [comment]
As this isn't an issue with mycroft-core, I'm going to close this issue. 

I'd encourage you to do a post in the forums or jump into the linux packaging channel on Mycroft Chat.

**Comment by Xanaxus** [comment]
> @Xanaxus are you using Anaconda? I was able to solve this issue by disabling my conda environment, then starting Mycroft

No I am not using an anaconda environment it's the first time I am hear of it.
