### ISSUE TITLE
MyCroft never responds to wakeword

### ISSUE THREAD

**Issue by PureTryOut** [MycroftAI/mycroft-core#2774]
**Describe the bug**
Although it seems to pick up the mic properly according to `mycroft-cli-client` (I see the volume bar go up and down if I talk), MyCroft never starts listening to commands.

**To Reproduce**
I'm unsure how to reproduce this, I think you just need an Alpine Linux system but I'm unsure if it's related to the OS in use.
Just run MyCroft as normal and try to give it a command.

**Expected behavior**
MyCroft to start listening for a command when I say it's wakeword.

**Log files**
It seems the voice module loads correctly:

```
2020-12-08 15:51:59.805 | INFO     | 31744 | mycroft.client.speech.hotword_factory:load_module:432 | Loading "hey mycroft" wake word via pocketsphinx
2020-12-08 15:51:59.856 | INFO     | 31744 | mycroft.client.speech.listener:create_wakeup_recognizer:365 | creating stand up word engine
2020-12-08 15:51:59.857 | INFO     | 31744 | mycroft.client.speech.hotword_factory:load_module:432 | Loading "wake up" wake word via pocketsphinx
2020-12-08 15:51:59.876 | INFO     | 31744 | mycroft.client.speech.__main__:on_ready:175 | Speech client is ready.
2020-12-08 15:51:59.900 | INFO     | 31744 | mycroft.messagebus.client.client:on_open:114 | Connected
```

**Environment (please complete the following information):**
 - Device type: desktop
 - OS: Alpine Linux
 - Mycroft-core version: 20.08

**Additional context**
This happens with both system packages and `dev_setup.sh`, so I doubt it's related to my distribution packaging efforts.

**Comment by el-tocino** [comment]
You should change over to precise instead of pocketsphinx, it's a much better wakeword spotter.

**Comment by PureTryOut** [comment]
That would be lovely but no can do:

```
2020-12-08 15:45:02.607 | ERROR    | 29535 | mycroft.client.speech.hotword_factory:initialize:478 | Could not create hotword. Falling back to default.
Traceback (most recent call last):
  File "/home/bart/Documents/Git/mycroft/mycroft-core/mycroft/client/speech/hotword_factory.py", line 467, in initialize
    instance = clazz(hotword, config, lang=lang)
  File "/home/bart/Documents/Git/mycroft/mycroft-core/mycroft/client/speech/hotword_factory.py", line 230, in __init__
    self.runner.start()
  File "/home/bart/Documents/Git/mycroft/mycroft-core/.venv/lib/python3.8/site-packages/precise_runner/runner.py", line 159, in start
    self.engine.start()
  File "/home/bart/Documents/Git/mycroft/mycroft-core/.venv/lib/python3.8/site-packages/precise_runner/runner.py", line 53, in start
    self.proc = Popen(self.exe_args, stdin=PIPE, stdout=PIPE)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/bart/.mycroft/precise/precise-engine/precise-engine'
```

(which afaik is due to downloading some pre-compiled stuff which doesn't work with Musl)

**Comment by el-tocino** [comment]
If pocketsphinx worked fine previously, then what's changed?

Can you manually download precise? It would work much better.

**Comment by PureTryOut** [comment]
It might work better, but it doesn't matter much in this case. PocketSphinx is a supported option, so it should work.

As for what might have happened, I guess a PocketSphinx update or something? At least, I would blame that for distro packaging as I use a newer version there than MyCroft requirese, but the fact that it's broken with `dev_setup.sh` makes me think that isn't the case.
So no clue what changed, I wish I knew :wink:

**Comment by andyslucky** [comment]
Have you tried changing your wake word from the default? I experienced the same issue, but once I changed the wake word to "Christopher" everything worked fine.

**Comment by PureTryOut** [comment]
I did yes (I prefer "Hey Jarvis" over "Hey MyCroft"), no luck.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
