### ISSUE TITLE
stop input returns multiple errors

### ISSUE THREAD

**Issue by goldyfruit** [MycroftAI/mycroft-core#2826]
When using the `stop` command from the CLI it returns an error on 4 different skills.

I'm using the `dev` version with the latest commit.

![image](https://user-images.githubusercontent.com/614115/107107131-3cd65b80-67fd-11eb-9c55-12a9893d4c9b.png)

Errors from the `skills.log`:
```
2021-02-06 02:57:32.214 - OVOS - ovos_utils.waiting_for_mycroft.base_skill:on_error:155 - ERROR - An error occurred while processing a request in Playback Control Skill
Traceback (most recent call last):
  File "/home/mycroft/core/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
    handler(message)
  File "/opt/mycroft-venv/lib/python3.7/site-packages/ovos_utils/waiting_for_mycroft/base_skill.py", line 184, in __handle_stop
    super().__handle_stop()
TypeError: __handle_stop() missing 1 required positional argument: '_'
2021-02-06 02:57:32.247 - OVOS - ovos_utils.waiting_for_mycroft.base_skill:on_error:155 - ERROR - An error occurred while processing a request in Joking Skill
Traceback (most recent call last):
  File "/home/mycroft/core/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
    handler(message)
  File "/opt/mycroft-venv/lib/python3.7/site-packages/ovos_utils/waiting_for_mycroft/base_skill.py", line 184, in __handle_stop
    super().__handle_stop()
TypeError: __handle_stop() missing 1 required positional argument: '_'
2021-02-06 02:57:32.252 - OVOS - ovos_utils.waiting_for_mycroft.base_skill:on_error:155 - ERROR - An error occurred while processing a request in Timer Skill
Traceback (most recent call last):
  File "/home/mycroft/core/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
    handler(message)
  File "/opt/mycroft-venv/lib/python3.7/site-packages/ovos_utils/waiting_for_mycroft/base_skill.py", line 184, in __handle_stop
    super().__handle_stop()
TypeError: __handle_stop() missing 1 required positional argument: '_'
2021-02-06 02:57:32.254 - OVOS - ovos_utils.waiting_for_mycroft.base_skill:on_error:155 - ERROR - An error occurred while processing a request in News Skill
Traceback (most recent call last):
  File "/home/mycroft/core/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
    handler(message)
  File "/opt/mycroft-venv/lib/python3.7/site-packages/ovos_utils/waiting_for_mycroft/base_skill.py", line 184, in __handle_stop
    super().__handle_stop()
TypeError: __handle_stop() missing 1 required positional argument: '_'
```

**Comment by goldyfruit** [comment]
Seems to be an `ovos_utils` issue, I opened an issue there: https://github.com/OpenVoiceOS/ovos_utils/issues/41
