### ISSUE TITLE
Docker image error: "pa_context_connect() failed: Connection refused" with audiotest

### ISSUE THREAD

**Issue by auwsom** [MycroftAI/mycroft-core#3037]
Fresh docker image following the install docker at link below, so I would expect it to work out of the box. Using `docker exec -it mycroft /bin/bash` to start. Then `mycroft-start audiotest` and I get the error in the title. I've seen this error, I think when setting up Mycroft in a VM and it was because I had installed as root. I'm a little confused here because the Docker container doesnt have a user beside root. 

The packages are installed into /opt so I might assume I'm supposed to create a user, so I did, and use the command below to start the container with that user, but I get another error: 

```
Changing ownership of /opt/mycroft to user: with group: abc
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
Starting audiotest
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
....
  File "/opt/mycroft/mycroft/configuration/config.py", line 17, in <module>
    import inflection
ModuleNotFoundError: No module named 'inflection'
```
I'm working through the errors for clues, but either way, the instructions for Docker below are lacking the necessary steps to make it work.

https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/get-mycroft/docker

**Comment by krisgesling** [comment]
Hey not sure why inflection is not installed - but if you're still using this image - to get past this specific error you can run `mycroft-pip install inflection` within the Docker container.

We'll need to look at why it's not getting installed though.
