### ISSUE TITLE
ERROR | 23789 | mycroft.skills.settings:_issue_api_call:306 | Failed to upload skill settings meta

### ISSUE THREAD

**Issue by semiexperienced** [MycroftAI/mycroft-core#3040]
**Describe the bug**
Fresh install on ubuntu runs into this error and will not utilize any skills.

```
requests.exceptions.HTTPError: {'skill_gid': ['Received skill setting definition before manifest for skill mycroft-joke|21.02']}
 20:44:01.183 | ERROR    | 23789 | mycroft.skills.settings:_issue_api_call:306 | Failed to upload skill settings meta for fallback-wolfram-alpha|21.02
Traceback (most recent call last):
  File "/home/sean/mycroft-core/mycroft/skills/settings.py", line 304, in _issue_api_call
    self.api.upload_skill_metadata(self.settings_meta)
  File "/home/sean/mycroft-core/mycroft/api/__init__.py", line 371, in upload_skill_metadata
    return self.request({
  File "/home/sean/mycroft-core/mycroft/api/__init__.py", line 64, in request
    return self.send(params)
  File "/home/sean/mycroft-core/mycroft/api/__init__.py", line 147, in send
    return self.get_response(response, no_refresh)
  File "/home/sean/mycroft-core/mycroft/api/__init__.py", line 170, in get_response
    raise HTTPError(data, response=response)
requests.exceptions.HTTPError: {'skill_gid': ['Received skill setting definition before manifest for skill fallback-wolfram-alpha|21.02']}
 20:44:01.191 | ERROR    | 23789 | mycroft.skills.settings:_issue_api_call:306 | Failed to upload skill settings meta for mycroft-wiki|21.02
Traceback (most recent call last):
  File "/home/sean/mycroft-core/mycroft/skills/settings.py", line 304, in _issue_api_call
    self.api.upload_skill_metadata(self.settings_meta)
  File "/home/sean/mycroft-core/mycroft/api/__init__.py", line 371, in upload_ski
```

**Comment by krisgesling** [comment]
Hey there, 

I can't seem to replicate this. Can I confirm how you are installing it?
`git clone https://github.com/mycroftai/mycroft-core`?

Did you select dev or master as the branch?

Did you receive a pairing code? Were you able to successfully pair with our backend?

**Comment by s-wel** [comment]
I ran into the same problem I think. I used the converse method and integrated a "stop" if-clause that "deactivates" my skill. 
The corresponding part looks like this:
```
if self.voc_match(message.data['utterances'][0], 'Stop'):
            self.bus.emit(
                Message(
                    "skillmanager.deactivate",
                    data={'skill': 'skill-rasa-chat.rasa-assistant'}
                )
            )
            self.stop()
else:
            intent_handlers.converse(skill=self, message=message)
```

After that, Mycroft returns a series of errors (for all skills it seems):

```
16:36:07.360 | ERROR    | 13866 | mycroft.skills.settings:_issue_api_call:306 | Failed to upload skill settings meta for mycroft-support-helper|21.02
Traceback (most recent call last):
  File "/home/u/mycroft-core/mycroft/skills/settings.py", line 304, in _issue_api_call
    self.api.upload_skill_metadata(self.settings_meta)
  File "/home/u/mycroft-core/mycroft/api/__init__.py", line 371, in upload_skill_metadata
    return self.request({
  File "/home/u/mycroft-core/mycroft/api/__init__.py", line 64, in request
    return self.send(params)
  File "/home/u/mycroft-core/mycroft/api/__init__.py", line 147, in send
    return self.get_response(response, no_refresh)
  File "/home/u/mycroft-core/mycroft/api/__init__.py", line 170, in get_response
    raise HTTPError(data, response=response)
requests.exceptions.HTTPError: {'skill_gid': ['Received skill setting definition before manifest for skill mycroft-support-helper|21.02']}
```
The strange think is that I use version 21.2.2 on my laptop with a WSL2 Ubuntu...the error indicates something for 21.02.
The only think that stops the behavior is a restart.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
