### ISSUE TITLE
Custom wake word not working [BrokenPipeError: [Errno 32] Broken pipe]

### ISSUE THREAD

**Issue by ZarvaanBacha** [MycroftAI/mycroft-core#3130]
**Describe the bug**
When Mycroft loads the custom Precise wakeword, an error occurs in which Tensorflow cannot start

**Log**

 19:29:30.619 | INFO     | 663538 | __main__:on_ready:179 | Speech client is ready.
[663593] Failed to execute script engine
Traceback (most recent call last):
  File "tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
  File "/home/matthew/Documents/GitHub/mycroft-precise/.venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
  File "imp.py", line 242, in load_module
  File "imp.py", line 342, in load_dynamic
ImportError: /home/zarvaan/.local/share/mycroft/precise/precise-engine/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN15stream_executor4cuda15kCudaPlatformIdE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "precise/scripts/engine.py", line 64, in <module>
  File "precise/scripts/engine.py", line 52, in main
  File "precise/network_runner.py", line 91, in __init__
  File "precise/network_runner.py", line 41, in __init__
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/matthew/Documents/GitHub/mycroft-precise/.venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "tensorflow/__init__.py", line 24, in <module>
  File "/home/matthew/Documents/GitHub/mycroft-precise/.venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "tensorflow/python/__init__.py", line 49, in <module>
  File "/home/matthew/Documents/GitHub/mycroft-precise/.venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
ImportError: Traceback (most recent call last):
  File "tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
  File "/home/matthew/Documents/GitHub/mycroft-precise/.venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
  File "imp.py", line 242, in load_module
  File "imp.py", line 342, in load_dynamic
ImportError: /home/zarvaan/.local/share/mycroft/precise/precise-engine/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN15stream_executor4cuda15kCudaPlatformIdE

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Exception in thread Thread-5 (_handle_predictions):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zarvaan/mycroft-core/.venv/lib/python3.10/site-packages/precise_runner/runner.py", line 197, in _handle_predictions
    prob = self.engine.get_prediction(chunk)
  File "/home/zarvaan/mycroft-core/.venv/lib/python3.10/site-packages/precise_runner/runner.py", line 64, in get_prediction self.proc.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

**To Reproduce**
> 1. start 'mycroft-start debug'

Log files
I could provide more if needed

Environment (please complete the following information):

Device type: Custom computer running Intel Core i7-8700K with GTX 1080
OS: Ubuntu 20.04
Mycroft-core version: v21.2.2

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
