### ISSUE TITLE
Issues installing on Pop OS - Unmet Dependancies

### ISSUE THREAD

**Issue by tony1661** [MycroftAI/mycroft-core#3134]
## Be clear about the software, hardware and version you are running

System 76 Thelio - Pop OS 22.04

## Try to provide steps that we can use to replicate the Issue

1. Ran through the standard install steps (git clone, cd, dev_setup)
2. Tried to run mycroft in cli and debug mode

## Be as specific as possible about the expected condition, and the deviation from expected condition. 

When running dev_setup, I get an error about unmet dependencies.

```
~/mycroft-core$ bash dev_setup.sh
Installing packages...
 Installing packages for Debian/Ubuntu/Mint...

We have detected that your computer has the libjack-jackd2-0 package installed.
Mycroft requires a conflicting package, and will likely uninstall this package.
On some systems, this can cause other programs to be marked for removal.
Please review the following package changes carefully.
Press enter to continue
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9ubuntu3).
build-essential set to manually installed.
libffi-dev is already the newest version (3.4.2-4).
libffi-dev set to manually installed.
libglib2.0-dev is already the newest version (2.72.1-1).
libglib2.0-dev set to manually installed.
libicu-dev is already the newest version (70.1-2).
libicu-dev set to manually installed.
pkg-config is already the newest version (0.29.2-1ubuntu3).
pkg-config set to manually installed.
pulseaudio-utils is already the newest version (1:15.99.1+dfsg1-1ubuntu1).
pulseaudio-utils set to manually installed.
curl is already the newest version (7.81.0-1ubuntu1.4).
curl set to manually installed.
git is already the newest version (1:2.34.1-1ubuntu1.4).
git set to manually installed.
python3 is already the newest version (3.10.6-1~22.04).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pop-desktop : Conflicts: pulseaudio
               Recommends: io.elementary.sideload but it is not installable
               Conflicts: pulseaudio:i386
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

## Provide log files or other output to help us see the error

Here are some output from when I try to run the service:

```
~/mycroft-core$ ./start-mycroft.sh debug
Please update dependencies by running ./dev_setup.sh again.
```

```
~/mycroft-core$ ./start-mycroft.sh cli
Initializing...
./start-mycroft.sh: line 83: /home/tfernandez/mycroft-core/.venv/bin/activate: No such file or directory
Starting background service bus
CAUTION: The Mycroft bus is an open websocket with no built-in security
         measures.  You are responsible for protecting the local port
         8181 with a firewall as appropriate.
Starting background service skills
Starting cli
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/tfernandez/mycroft-core/mycroft/__init__.py", line 17, in <module>
    from mycroft.api import Api
  File "/home/tfernandez/mycroft-core/mycroft/api/__init__.py", line 22, in <module>
    from mycroft.configuration import Configuration
  File "/home/tfernandez/mycroft-core/mycroft/configuration/__init__.py", line 15, in <module>
    from .config import Configuration, LocalConf, RemoteConf
  File "/home/tfernandez/mycroft-core/mycroft/configuration/config.py", line 17, in <module>
    import inflection
ModuleNotFoundError: No module named 'inflection'
```

**Comment by tony1661** [comment]
It seems like I was able to get past this by excluding pulseaudio from the `APT_PACKAGE_LIST` in the `dev_setup.sh` file.

It seems the issue may be related to pipewire being used instead of pulseaudio.

Since pipewire-pulseaudio is already installed for apps that rely on pulseaudio, everything appears to be working.

**Comment by jswhisperer** [comment]
Found this also  https://snapcraft.io/install/mycroft-precise/pop#install

Would be cool is the there was a link to installation somewhere if the contributes get time.

**Comment by JarbasAl** [comment]
hello, mycroftAI is dead, and has been for quite some time now, there is no support or updates coming

you might be interested in OpenVoiceOS, a non-profit foundation that forked Mycroft and continued development https://openvoiceos.org

**Comment by jswhisperer** [comment]
Aw thanks just noticed that on the pairing step, appreciate the alternative!
