### ISSUE TITLE
ModuleNotFoundError: No module named 'xdg.BaseDirectory'

### ISSUE THREAD

**Issue by yjdwbj** [MycroftAI/mycroft-core#3156]
**Describe the bug**
Hi, all. I cloned mycroft-core on my computer and installed it. But I get the following error when running.

**To Reproduce**
```sh
~$ source .venv/bin/activate
(.venv) blink@blink-eq:~/mycroft-core$ mycroft-skill-testrunner 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/blink/mycroft-core/test/integrationtests/skills/runner.py", line 32, in <module>
    from test.integrationtests.skills.skill_tester import MockSkillsLoader
  File "/home/blink/mycroft-core/test/integrationtests/skills/skill_tester.py", line 44, in <module>
    from mycroft.messagebus.message import Message
  File "/home/blink/mycroft-core/mycroft/__init__.py", line 17, in <module>
    from mycroft.api import Api
  File "/home/blink/mycroft-core/mycroft/api/__init__.py", line 22, in <module>
    from mycroft.configuration import Configuration
  File "/home/blink/mycroft-core/mycroft/configuration/__init__.py", line 15, in <module>
    from .config import Configuration, LocalConf, RemoteConf
  File "/home/blink/mycroft-core/mycroft/configuration/config.py", line 22, in <module>
    import xdg.BaseDirectory
ModuleNotFoundError: No module named 'xdg.BaseDirectory'

(.venv) blink@blink-eq:~/mycroft-core$ mycroft-pip install xdg
Requirement already satisfied: xdg in ./.venv/lib/python3.11/site-packages (6.0.0)

```

**Expected behavior**

**Log files**
If possible, add log files from `/var/log/mycroft/` to help explain your problem.

You may also include screenshots, however screenshots of log files are often difficult to read and parse. 

If you are running Mycroft, the [Support Skill](https://github.com/MycroftAI/skill-support) helps to automate gathering this information. Simply say "Create a support ticket" and the Skill will put together a support package and email it to you.

**Environment (please complete the following information):**
 - Device type: [ desktop x86_64]
 - OS: [debian bookworm]
 - Mycroft-core version: [ git main ]
 - Other versions: [e.g. Adapt v0.3.7]

**Comment by forslund** [comment]
Closing PR since we're archiving the repo
