### ISSUE TITLE
Error building on Raspberry Pi OS bookworm.

### ISSUE THREAD

**Issue by mocallins** [MycroftAI/mycroft-core#3159]
**Describe the bug**

**To Reproduce**
4. See error '....'

**Expected behavior**

**Log files**
If possible, add log files from `/var/log/mycroft/` to help explain your problem.

You may also include screenshots, however screenshots of log files are often difficult to read and parse. 

If you are running Mycroft, the [Support Skill](https://github.com/MycroftAI/skill-support) helps to automate gathering this information. Simply say "Create a support ticket" and the Skill will put together a support package and email it to you.

**Environment (please complete the following information):**
 - Device type: [e.g. Raspberry Pi, Mark 1, desktop]
 - OS: [e.g. Ubuntu, Picroft]
 - Mycroft-core version: [e.g. 20.08]
 - Other versions: [e.g. Adapt v0.3.7]

**Additional context**

Please think carefully about whether you have modified anything in Mycroft's code or configuration files.  If so, can you reproduce this on a clean installation of Mycroft? Many "bugs" turn out to be non-standard configuration errors.

**Comment by mocallins** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. bash dev_setup.sh
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
Install as expected.

> 
> **Log files** If possible, add log files from `/var/log/mycroft/` to help explain your problem.
attached


> 
> You may also include screenshots, however screenshots of log files are often difficult to read and parse.
```Collecting PyYAML~=5.4
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/pi/build/mycroft-core/.venv/bin/python3 /home/pi/build/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpxazr9m78
       cwd: /tmp/pip-install-eq8949ts/PyYAML
  Complete output (68 lines):
  /tmp/pip-build-env-7lfiu647/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
  !!

          ********************************************************************************
          The license_file parameter is deprecated, use license_files instead.

          This deprecation is overdue, please update your project and remove deprecated
          calls to avoid build errors in the future.

          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
          ********************************************************************************

  !!
    parsed = self.parsers.get(option_name, lambda x: x)(value)
  running egg_info
  writing lib3/PyYAML.egg-info/PKG-INFO
  writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
  writing top-level names to lib3/PyYAML.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/home/pi/build/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/home/pi/build/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/pi/build/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-7lfiu647/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-7lfiu647/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-7lfiu647/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 271, in <module>
    File "/tmp/pip-build-env-7lfiu647/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-7lfiu647/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-7lfiu647/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-7lfiu647/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-7lfiu647/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-7lfiu647/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-7lfiu647/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 318, in run
      self.find_sources()
    File "/tmp/pip-build-env-7lfiu647/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 326, in find_sources
      mm.run()
    File "/tmp/pip-build-env-7lfiu647/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 548, in run
      self.add_defaults()
    File "/tmp/pip-build-env-7lfiu647/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 586, in add_defaults
      sdist.add_defaults(self)
    File "/tmp/pip-build-env-7lfiu647/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
      super().add_defaults()
    File "/tmp/pip-build-env-7lfiu647/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
      self._add_defaults_ext()
    File "/tmp/pip-build-env-7lfiu647/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<string>", line 201, in get_source_files
    File "/tmp/pip-build-env-7lfiu647/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources
  
ERROR: Command errored out with exit status 1: /home/pi/build/mycroft-core/.venv/bin/python3 /home/pi/build/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpxazr9m78 Check the logs for full command output.
Warning: Failed to install required dependencies. Continue? y/N
y```

> 
> If you are running Mycroft, the [Support Skill](https://github.com/MycroftAI/skill-support) helps to automate gathering this information. Simply say "Create a support ticket" and the Skill will put together a support package and email it to you.
> 
> **Environment (please complete the following information):**
> 
> * Device type: Raspberry Pi
> * OS: Raspberry Pi OS bookworm
> * Mycroft-core version: current source
> *
> 
> **Additional context** Add any other context about the problem here.
> 
> Please think carefully about whether you have modified anything in Mycroft's code or configuration files. If so, can you reproduce this on a clean installation of Mycroft? Many "bugs" turn out to be non-standard configuration errors.

[audio.log](https://github.com/MycroftAI/mycroft-core/files/13257864/audio.log)
[bus.log](https://github.com/MycroftAI/mycroft-core/files/13257865/bus.log)
[enclosure.log](https://github.com/MycroftAI/mycroft-core/files/13257866/enclosure.log)
[setup.log](https://github.com/MycroftAI/mycroft-core/files/13257867/setup.log)
[skills.log](https://github.com/MycroftAI/mycroft-core/files/13257868/skills.log)
[voice.log](https://github.com/MycroftAI/mycroft-core/files/13257869/voice.log)

**Comment by forslund** [comment]
Closing PR since we're archiving the repo
