### ISSUE TITLE
 SkillRepo init error while setting up mycroft

### ISSUE THREAD

**Issue by lumy** [MycroftAI/mycroft-core#3161]
**Describe the bug**
while trying to install and test mycroft i've come accros an error.
When i start with the  script `start-mycroft.sh` the log files show some errors.

**To Reproduce**
follow the guide from: https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/get-mycroft/linux

**Log files**
```
==> skills.log <==
  File "/home/lumy/Kernel/mycroft-core/mycroft/skills/skill_updater.py", line 58, in __init__
    self.dot_msm_path = os.path.join(self.msm.skills_dir, '.msm')
                                     ^^^^^^^^
  File "/home/lumy/Kernel/mycroft-core/mycroft/skills/skill_updater.py", line 111, in msm
    self._msm = create_msm(msm_config)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lumy/Kernel/mycroft-core/mycroft/skills/msm_wrapper.py", line 101, in create_msm
    msm_skill_repo = SkillRepo(
                     ^^^^^^^^^^
TypeError: SkillRepo.__init__() takes from 1 to 3 positional arguments but 4 were given
```
```
==> voice.log <==
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
2023-12-20 22:00:02.633 | INFO     | 20673 | mycroft.client.speech.listener:create_wake_word_recognizer:328 | Creating wake word engine
2023-12-20 22:00:02.639 | INFO     | 20673 | mycroft.client.speech.listener:create_wake_word_recognizer:351 | Using hotword entry for hey mycroft
2023-12-20 22:00:02.644 | INFO     | 20673 | mycroft.client.speech.hotword_factory:load_module:500 | Loading "hey mycroft" wake word via precise
2023-12-20 22:00:04.258 | INFO     | 20673 | mycroft.client.speech.hotword_factory:on_download:322 | Downloading Precise executable...
2023-12-20 22:00:09.268 | INFO     | 20673 | mycroft.client.speech.hotword_factory:during_download:334 | Still downloading executable...
2023-12-20 22:00:12.661 | INFO     | 20673 | mycroft.client.speech.hotword_factory:load_module:535 | precise is taking too long to load
2023-12-20 22:00:12.668 | INFO     | 20673 | mycroft.client.speech.hotword_factory:load_module:500 | Loading "hey mycroft" wake word via pocketsphinx
ERROR: "ps_config.c", line 158: Only one of lm, jsgf, fsg, keyphrase, kws, allphone, lmctl, can be enabled at a time in config
2023-12-20 22:00:12.677 | ERROR    | 20673 | mycroft.client.speech.hotword_factory:initialize:528 | Could not create hotword. Falling back to default.
Traceback (most recent call last):
  File "/home/lumy/Kernel/mycroft-core/mycroft/client/speech/hotword_factory.py", line 513, in initialize
    instance = clazz(hotword, config, lang=lang)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lumy/Kernel/mycroft-core/mycroft/client/speech/hotword_factory.py", line 142, in __init__
    self.decoder = Decoder(config)
                   ^^^^^^^^^^^^^^^
  File "_pocketsphinx.pyx", line 852, in _pocketsphinx.Decoder.__init__
RuntimeError: Failed to initialize PocketSphinx
ERROR: "ps_config.c", line 158: Only one of lm, jsgf, fsg, keyphrase, kws, allphone, lmctl, can be enabled at a time in config
2023-12-20 22:00:12.792 | ERROR    | 20673 | __main__:on_error:187 | Audio service failed to launch (RuntimeError('Failed to initialize PocketSphinx')).
```
**Environment (please complete the following information):**
 - Device type: Desktop Debian 12
 - Mycroft-core version: (tested on master and release/v21.2.2)

**Comment by JarbasAl** [comment]
Mycroft is dead and there is no one to give you support

I recommend you move to either OVOS or Neon which are the surviving forks of mycroft, both are very active and updated often

**Comment by forslund** [comment]
Closing PR since we're archiving the repo
