### ISSUE TITLE
dev_setup.sh fails because of PyYAML on armv7 Armbian 23.11.1 Bookworm

### ISSUE THREAD

**Issue by dzianisv** [MycroftAI/mycroft-core#3162]
**Describe the bug**
dev_setup fails to install all the dependencies. 
Looks similar to https://github.com/MycroftAI/mycroft-core/issues/3159

**To Reproduce**
```shell
git clone https://github.com/MycroftAI/mycroft-core.git
cd mycroft-core
bash dev_setup.sh
```

**Expected behavior**
Dev environment installed 

**Log files**
```
ERROR: Command errored out with exit status 1:
   command: /home/user/mycroft-core/.venv/bin/python3 /home/user/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp5d5jl_6b
       cwd: /tmp/pip-install-yuf0lyg6/PyYAML
  Complete output (54 lines):
  running egg_info
  writing lib3/PyYAML.egg-info/PKG-INFO
  writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
  writing top-level names to lib3/PyYAML.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/home/user/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/home/user/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/user/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-p1azvwhy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-p1azvwhy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-p1azvwhy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 271, in <module>
    File "/tmp/pip-build-env-p1azvwhy/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-p1azvwhy/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-p1azvwhy/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-p1azvwhy/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-p1azvwhy/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-p1azvwhy/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-p1azvwhy/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 321, in run
      self.find_sources()
    File "/tmp/pip-build-env-p1azvwhy/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
      mm.run()
    File "/tmp/pip-build-env-p1azvwhy/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
      self.add_defaults()
    File "/tmp/pip-build-env-p1azvwhy/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
      sdist.add_defaults(self)
    File "/tmp/pip-build-env-p1azvwhy/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
      super().add_defaults()
    File "/tmp/pip-build-env-p1azvwhy/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
      self._add_defaults_ext()
    File "/tmp/pip-build-env-p1azvwhy/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<string>", line 201, in get_source_files
    File "/tmp/pip-build-env-p1azvwhy/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/user/mycroft-core/.venv/bin/python3 /home/user/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp5d5jl_6b Check the logs for full command output.
```

**Environment (please complete the following information):**
 - Device type: OrangePi PC, armv7
 - OS: Ubuntu, Armbian 23.11.1 Bookworm
 - Kernel: Linux orangepipc 6.1.63-current-sunxi #1 SMP Mon Nov 20 10:52:19 UTC 2023 armv7l GNU/Linux
 - Mycroft-core version: from master
 - Other versions: [e.g. Adapt v0.3.7]

**Additional context**

**Comment by dzianisv** [comment]
Solution: 
```diff
diff --git a/dev_setup.sh b/dev_setup.sh
index d73be87c0f..ebfb499dff 100755
--- a/dev_setup.sh
+++ b/dev_setup.sh
@@ -545,8 +545,10 @@ if ! grep -q "$TOP" $VENV_PATH_FILE ; then
 ' "$VENV_PATH_FILE"
 fi
 
+echo 'Cython < 3.0' > /tmp/constraint.txt
+PIP_CONSTRAINT=/tmp/constraint.txt pip wheel PyYAML==5.4.1
 # install required python modules
-if ! pip install -r requirements/requirements.txt ; then
+if ! PIP_CONSTRAINT=/tmp/constraint.txt pip install -r requirements/requirements.txt ; then
     echo 'Warning: Failed to install required dependencies. Continue? y/N'
     read -n1 continue
     if [[ $continue != 'y' ]] ; then
```

next issue, 
``` 
warning: no previously-included files found matching 'ci-constraints-requirements.txt'
  warning: no previously-included files found matching 'mypy.ini'
  adding license file 'LICENSE'
  adding license file 'LICENSE.APACHE'
  adding license file 'LICENSE.BSD'
  writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
  copying src/cryptography/py.typed -> build/lib.linux-armv7l-cpython-311/cryptography
  creating build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust
  copying src/cryptography/hazmat/bindings/_rust/__init__.pyi -> build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust
  copying src/cryptography/hazmat/bindings/_rust/_openssl.pyi -> build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust
  copying src/cryptography/hazmat/bindings/_rust/asn1.pyi -> build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust
  copying src/cryptography/hazmat/bindings/_rust/exceptions.pyi -> build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust
  copying src/cryptography/hazmat/bindings/_rust/ocsp.pyi -> build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust
  copying src/cryptography/hazmat/bindings/_rust/pkcs7.pyi -> build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust
  copying src/cryptography/hazmat/bindings/_rust/x509.pyi -> build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust
  creating build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust/openssl
  copying src/cryptography/hazmat/bindings/_rust/openssl/__init__.pyi -> build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust/openssl
  copying src/cryptography/hazmat/bindings/_rust/openssl/dh.pyi -> build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust/openssl
  copying src/cryptography/hazmat/bindings/_rust/openssl/dsa.pyi -> build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust/openssl
  copying src/cryptography/hazmat/bindings/_rust/openssl/ed25519.pyi -> build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust/openssl
  copying src/cryptography/hazmat/bindings/_rust/openssl/ed448.pyi -> build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust/openssl
  copying src/cryptography/hazmat/bindings/_rust/openssl/hashes.pyi -> build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust/openssl
  copying src/cryptography/hazmat/bindings/_rust/openssl/hmac.pyi -> build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust/openssl
  copying src/cryptography/hazmat/bindings/_rust/openssl/kdf.pyi -> build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust/openssl
  copying src/cryptography/hazmat/bindings/_rust/openssl/poly1305.pyi -> build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust/openssl
  copying src/cryptography/hazmat/bindings/_rust/openssl/x25519.pyi -> build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust/openssl
  copying src/cryptography/hazmat/bindings/_rust/openssl/x448.pyi -> build/lib.linux-armv7l-cpython-311/cryptography/hazmat/bindings/_rust/openssl
  running build_ext
  running build_rust
  
      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation/ for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq/
      4) Ensure you have a recent Rust toolchain installed:
         https://cryptography.io/en/latest/installation/#rust
  
      Python: 3.11.2
      platform: Linux-6.1.63-current-sunxi-armv7l-with-glibc2.36
      pip: n/a
      setuptools: 69.0.3
      setuptools_rust: 1.8.1
      rustc: n/a
      =============================DEBUG ASSISTANCE=============================
  
  error: can't find Rust compiler
  
  If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
  
  To update pip, run:
  
      pip install --upgrade pip
  
  and then retry package installation.
  
  If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
  
  This package requires Rust >=1.56.0.
  ----------------------------------------
  ERROR: Failed building wheel for cryptography```

**Comment by dzianisv** [comment]
Workaround:
```shell
sudo apt install -yq rustc cargo
```

**Comment by dzianisv** [comment]
Failed again
```
    CC_armv7-unknown-linux-gnueabihf = None
    cargo:rerun-if-env-changed=CC_armv7_unknown_linux_gnueabihf
    CC_armv7_unknown_linux_gnueabihf = None
    cargo:rerun-if-env-changed=HOST_CC
    HOST_CC = None
    cargo:rerun-if-env-changed=CC
    CC = None
    cargo:rerun-if-env-changed=CFLAGS_armv7-unknown-linux-gnueabihf
    CFLAGS_armv7-unknown-linux-gnueabihf = None
    cargo:rerun-if-env-changed=CFLAGS_armv7_unknown_linux_gnueabihf
    CFLAGS_armv7_unknown_linux_gnueabihf = None
    cargo:rerun-if-env-changed=HOST_CFLAGS
    HOST_CFLAGS = None
    cargo:rerun-if-env-changed=CFLAGS
    CFLAGS = None
    cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
    CRATE_CC_NO_DEFAULTS = None
    CARGO_CFG_TARGET_FEATURE = None
    running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=armv7-a" "-mfpu=vfpv3-d16" "-I" "/usr/include/python3.11" "-I" "/usr/include" "-Wall" "-Wextra" "-Wconversion" "-Wno-error=sign-conversion" "-Wno-unused-parameter" "-DPy_LIMITED_API=0x030700f0" "-o" "/tmp/pip-install-_zqipnud/cryptography/src/rust/target/release/build/cryptography-cffi-05ed793b153fb111/out/0b756912ffed4081-_openssl.o" "-c" "/tmp/pip-install-_zqipnud/cryptography/src/rust/target/release/build/cryptography-cffi-05ed793b153fb111/out/_openssl.c"
    cargo:warning=/tmp/pip-install-_zqipnud/cryptography/src/rust/target/release/build/cryptography-cffi-05ed793b153fb111/out/_openssl.c:35560:11: fatal error: error writing to /tmp/cc87Gz4k.s: No space left on device
    cargo:warning=35560 | #  pragma GCC visibility pop
    cargo:warning=      |           ^~~
    cargo:warning=compilation terminated.
    exit status: 1
  
    --- stderr
  
  
    error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=armv7-a" "-mfpu=vfpv3-d16" "-I" "/usr/include/python3.11" "-I" "/usr/include" "-Wall" "-Wextra" "-Wconversion" "-Wno-error=sign-conversion" "-Wno-unused-parameter" "-DPy_LIMITED_API=0x030700f0" "-o" "/tmp/pip-install-_zqipnud/cryptography/src/rust/target/release/build/cryptography-cffi-05ed793b153fb111/out/0b756912ffed4081-_openssl.o" "-c" "/tmp/pip-install-_zqipnud/cryptography/src/rust/target/release/build/cryptography-cffi-05ed793b153fb111/out/_openssl.c" with args "cc" did not execute successfully (status code exit status: 1).
  
  
  
      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation/ for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq/
      4) Ensure you have a recent Rust toolchain installed:
         https://cryptography.io/en/latest/installation/#rust
  
      Python: 3.11.2
      platform: Linux-6.1.63-current-sunxi-armv7l-with-glibc2.36
      pip: n/a
      setuptools: 69.0.3
      setuptools_rust: 1.8.1
      rustc: n/a
      =============================DEBUG ASSISTANCE=============================
  
  error: `cargo rustc --lib --message-format=json-render-diagnostics --manifest-path src/rust/Cargo.toml --release -v --features pyo3/extension-module -- --crate-type cdylib` failed with code 101
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
```

**Comment by goldyfruit** [comment]
@dzianisv Mycroft AI is not in business anymore, there are forks such as OVOS and Neon which continue the project.

You can check as well https://github.com/OpenVoiceOS/ovos-installer which is the equivalent of `dev_script.sh` but for OVOS.

**Comment by dzianisv** [comment]
oh, thanks
