### ISSUE TITLE
Asking Mycroft for the time generates error

### ISSUE THREAD

**Issue by jswalls110** [MycroftAI/mycroft-core#431]
RPi 3 Mycroft apt-get upgraded mycroft-core this morning

When I ask Mycroft for the time it generates the following error:

2016-12-22 10:35:12,878 - SpeechClient - INFO - Wakeword Detected: hey mycroft
2016-12-22 10:35:12,933 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): api.mycroft.ai
2016-12-22 10:35:13,496 - requests.packages.urllib3.connectionpool - DEBUG - "POST /v1/stt?lang=en-US&limit=1 HTTP/1.1" 200 None
2016-12-22 10:35:14,089 - mycroft.client.speech.listener - DEBUG - STT: time is it
2016-12-22 10:35:14,089 - SpeechClient - INFO - Utterance: [u'time is it']
2016-12-22 10:35:14,406 - SpeechClient - INFO - Speak: An error occurred while processing a request in TimeSkill
Playing WAVE '/tmp/tts.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Mono

**Comment by jswalls110** [comment]
From the skills log file:

2016-12-22 14:51:32,311 - mycroft.skills.core - ERROR - An error occurred while processing a request in TimeSkill
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-1482384270-py2.7.egg/mycroft/skills/core.py", line 200, in receive_handler
    handler(message)
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-1482384270-py2.7.egg/mycroft/skills/date_time/__init__.py", line 62, in handle_intent
    tz = tzlocal.get_localzone()
  File "/usr/local/lib/python2.7/site-packages/tzlocal/unix.py", line 122, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python2.7/site-packages/tzlocal/unix.py", line 61, in _get_localzone
    return pytz.timezone(etctz.replace(' ', '_'))
  File "/usr/local/lib/python2.7/site-packages/pytz/__init__.py", line 181, in timezone
    raise UnknownTimeZoneError(zone)
UnknownTimeZoneError: 'SystemV/EST5'

**Comment by jswalls110** [comment]
This is solved by:

Run the command sudo dpkg-reconfigure tzdata . Use the up/down arrows to select the appropriate location and press enter. Use the up/down arrows (again) to select the appropriate timezone (closest city in your timezone) and press enter. The Raspberry Pi will acknowledge the timezone change

You can then choose the appropriate tz instead of a SystemV timezone
