### ISSUE TITLE
ImportError: No module named recognizer_wrapper

### ISSUE THREAD

**Issue by ciddu2000** [MycroftAI/mycroft-core#442]
hello everyone, i just Set up the development environment by following the method describe here : "https://docs.mycroft.ai/development/getting.started", i'm using linux mint 18.1 with cinnamon desktop environment.

i can't get it working for the moment, when i run the command "./mycroft.sh start" i ve got this error :

Mycroft service started
Mycroft skills started
mycroft-voice failed to start. The log is below:

2016-12-31 14:31:08,322 - mycroft.configuration - DEBUG - Configuration '/home/gaut/.mycroft/mycroft.conf' loaded
2016-12-31 14:31:08,443 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): api.mycroft.ai
2016-12-31 14:31:09,023 - requests.packages.urllib3.connectionpool - DEBUG - "GET /v1/device//setting HTTP/1.1" 401 38
2016-12-31 14:31:09,027 - mycroft.configuration - WARNING - Failed to fetch remote configuration: HTTPError(u'The supplied authentication is invalid',)
Traceback (most recent call last):
  File "/home/gaut/mycroft-core/mycroft/client/speech/main.py", line 24, in <module>
    from mycroft.client.speech.listener import RecognizerLoop
  File "/home/gaut/mycroft-core/mycroft/client/speech/listener.py", line 29, in <module>
    from mycroft.client.speech.recognizer_wrapper import \
ImportError: No module named recognizer_wrapper

**Comment by aatchison** [comment]
Hmm, were you able to run the `dev_setup.sh` script? That looks like you are missing some pip requirements. You might try:
`workon mycroft`
`pip install -r requirements.txt`

**Comment by ciddu2000** [comment]
so here's what i did :
i had to copy the content of that file : http://programtalk.com/vs2/?source=python/8955/mycroft-core/mycroft/client/speech/recognizer_wrapper.py
in my mycroft-core directory
then there was still an error telling there was a cli.py file missing, so i copy the content of that file : http://programtalk.com/vs2/?source=python/8955/mycroft-core/mycroft/client/text/cli.py
and then there was a last error telling the file mycroft-cli--quiet.log doesn't exist, so i copy mycroft-cli.log and renamed it mycroft-cli--quiet.log .

**Comment by aatchison** [comment]
Did you make any progress?

**Comment by aatchison** [comment]
There seems to be an issue when running screen for some people, any luck here?
Have you tried the start.sh method?

**Comment by hemangjoshi37a** [comment]
@aatchison, worked for me... thax....

**Comment by aatchison** [comment]
Np. Closing
