### ISSUE TITLE
HTTPError(u'The supplied authentication is invalid',)

### ISSUE THREAD

**Issue by nazarimilad** [MycroftAI/mycroft-core#444]
After downloading Mycroft Core, installing the development environment and running './mycroft.sh start', I get an error when I try to start the service process with './start.sh service'. I get the following error:  

`Starting service
2017-01-04 23:45:05,995 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): api.mycroft.ai
2017-01-04 23:45:06,875 - mycroft.configuration - WARNING - Failed to fetch remote configuration: HTTPError(u'The supplied authentication is invalid',)`
`
Traceback (most recent call last):
  File "/home/<computername>/Documents/Projecten/mycroft-core/mycroft/messagebus/service/main.py", line 53, in <module>
    main()
  File "/home/<computername>/Documents/Projecten/mycroft-core/mycroft/messagebus/service/main.py", line 48, in main
    application.listen(port, host)
  File "/home/<computername>/.virtualenvs/mycroft/local/lib/python2.7/site-packages/tornado/web.py", line 1788, in listen
    server.listen(port, address)
  File "/home/<computername>/.virtualenvs/mycroft/local/lib/python2.7/site-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/<computername>/.virtualenvs/mycroft/local/lib/python2.7/site-packages/tornado/netutil.py", line 187, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
`

I guess the port that Mycroft wants to use to listen is already used by another application? How can this problem be solved ?

**Comment by aatchison** [comment]
Hello!
`mycroft.sh start` and `./start.sh $service_name` actually do the same things.
I'm assuming that since you started all services in screen instances with `mycroft.sh start`, the message bus service is already running and therefore creating a conflict.

I personally like to use start.sh, so I can see the output of logs directly and start/stop them individually but mycroft.sh does some nice things such as starting and stopping all of the services, logging to scripts/logs, and allowing you to attach/detach from the screens they are running in. 

`ps aux |grep mycroft` should show some things already running.

**Comment by aatchison** [comment]
Also, the supplied authentication error is normal, it will do that until you pair the instance at `home.mycroft.ai`

**Comment by nazarimilad** [comment]
Oh that makes sense, thanks for the fast answer and the explanation!

**Comment by aatchison** [comment]
No problem, thanks for trying Mycroft! Let us know of any more issues you encounter.
