### ISSUE TITLE
Scary stack trace in unit tests

### ISSUE THREAD

**Issue by clusterfudge** [MycroftAI/mycroft-core#69]
```
.2016-05-28 14:17:38,085 - mycroft.client.speech.listener - DEBUG - STT: what's the weather next week
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/seanfitz/development/mycroft-core/mycroft/client/speech/listener.py", line 197, in runnable
    audio, metrics=self.metrics).lower()
  File "/home/seanfitz/development/mycroft-core/mycroft/client/speech/recognizer_wrapper.py", line 46, in transcribe
    audio, key=key, language=language, show_all=show_all)
  File "/home/seanfitz/development/mycroft-core/test/client/audio_consumer_test.py", line 38, in recognize_google
    return self.transcriptions.pop(0)
IndexError: pop from empty list
```

**Comment by ryanleesipes** [comment]
@ethanaward this is an error that was plaguing you. Was it fixed on rebase? If so I can close this issue.

**Comment by ryanleesipes** [comment]
Everything seems to be good now. Closing this.
