### ISSUE TITLE
Mycroft-voice crashes after wake word

### ISSUE THREAD

**Issue by BoBeR182** [MycroftAI/mycroft-core#713]
OS: Arch Linux
Version: e49184223fdfbee4a8d00b91fbe36bfb1133c4dc

Output from ```./start.sh voice``` 
```
[~/mycroft-core]% ./start.sh voice                                                                                                                                  [git][mycroft-core/.][devU]
Starting voice
2017-04-28 19:19:52,004 - mycroft.configuration - INFO - Loading configuration: /home/bober/mycroft-core/mycroft/configuration/mycroft.conf
2017-04-28 19:19:52,005 - mycroft.configuration - DEBUG - Configuration '/home/bober/mycroft-core/mycroft/configuration/mycroft.conf' loaded
2017-04-28 19:19:52,005 - mycroft.configuration - DEBUG - Configuration '/home/bober/.mycroft/mycroft.conf' not found
2017-04-28 19:19:52,005 - mycroft.configuration - INFO - Loading configuration: mycroft.ai
2017-04-28 19:19:52,075 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
2017-04-28 19:19:52,238 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device//setting HTTP/1.1" 401 38
2017-04-28 19:19:52,240 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
2017-04-28 19:19:52,412 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/auth/token HTTP/1.1" 401 38
2017-04-28 19:19:52,413 - mycroft.configuration - WARNING - Failed to fetch remote configuration: HTTPError(u'The supplied authentication is invalid',)
2017-04-28 19:19:52,413 - mycroft.configuration - INFO - Loading configuration: /etc/mycroft/mycroft.conf
2017-04-28 19:19:52,413 - mycroft.configuration - DEBUG - Configuration '/etc/mycroft/mycroft.conf' not found
2017-04-28 19:19:52,413 - mycroft.configuration - DEBUG - Configuration '/home/bober/.mycroft/mycroft.conf' not found
2017-04-28 19:19:52,413 - mycroft.configuration - INFO - Loading configuration: /home/bober/.mycroft/mycroft.conf
2017-04-28 19:19:52,413 - mycroft.configuration - DEBUG - Configuration '/home/bober/.mycroft/mycroft.conf' not found
2017-04-28 19:19:52,413 - mycroft.configuration - DEBUG - Configuration '/home/bober/.mycroft/mycroft.conf' not found
  Carnegie Mellon University, Copyright (c) 1999-2011, all rights reserved
  mimic developers, Copyright (c) 2016, all rights reserved
  version: mimic-1.2.0.2 ()
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
2017-04-28 19:19:52,664 - mycroft.messagebus.client.ws - INFO - Connected
2017-04-28 19:19:54,593 - mycroft.client.speech.mic - DEBUG - Waiting for wake word...
2017-04-28 19:20:10,397 - mycroft.client.speech.mic - DEBUG - Recording...
2017-04-28 19:20:10,397 - SpeechClient - INFO - Begin Recording...
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/bober/mycroft-core/mycroft/client/speech/listener.py", line 62, in run
    audio = self.recognizer.listen(source, self.emitter)
  File "/home/bober/mycroft-core/mycroft/client/speech/mic.py", line 412, in listen
    play_wav(file)
  File "/home/bober/mycroft-core/mycroft/util/__init__.py", line 91, in play_wav
    return subprocess.Popen(play_wav_cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by aatchison** [comment]
Thank you sir!

**Comment by BoBeR182** [comment]
Any updates, has anyone else been able to reproduce this bug?

**Comment by maxeeem** [comment]
I had a similar-looking error earlier today when I was trying to get mycroft to run on a Chromebook in a chroot. For me it was resolved by re-adding alsa-base library that was missing for some reason. Once i had `alsa-base` installed mycroft woke up! Hope this helps.

**Comment by forslund** [comment]
Sorry for this grave-digging. @maxeeem was in all likelyhood correct. Looks like the default executable for playing wav's were missing and the process raised an unhandled exception.

This has since been updated so play_wav handles these exceptions.

I'm going to close this issue for now.
