### ISSUE TITLE
intent_service.py - parse-problem causing crash.

### ISSUE THREAD

**Issue by hersche** [MycroftAI/mycroft-core#737]
hello,

i use ubuntu 17.04 and out of this, i did a git-setup. my problem is that i have this messages over and over:
```

2017-05-08 02:04:59,383 - Skills - DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "en-us", "utterances": ["\"hadn't\", \"hasn't\", \"haven't\", \"he'd\", \"he'll\", \"he's\","]}, "context": null}
2017-05-08 02:04:59,385 - mycroft.skills.intent_service - ERROR - 
Traceback (most recent call last):
  File "/home/hersche/mycroft-core/mycroft/skills/intent_service.py", line 53, in handle_utterance
    best_intent = next(self.engine.determine_intent(normalize(utterance, lang), 100))
StopIteration
2017-05-08 02:04:59,386 - Skills - DEBUG - {"type": "intent_failure", "data": {"lang": "en-us", "utterance": "\"hadn't\", \"hasn't\", \"haven't\", \"he'd\", \"he'll\", \"he's\","}, "context": null}
2017-05-08 02:04:59,466 - Skills - DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "en-us", "utterances": ["\"how'd\", \"how'll\", \"how's\", \"I'd\", \"I'll\", \"I'm\","]}, "context": null}
2017-05-08 02:04:59,467 - mycroft.skills.intent_service - ERROR - 
Traceback (most recent call last):
  File "/home/hersche/mycroft-core/mycroft/skills/intent_service.py", line 53, in handle_utterance
    best_intent = next(self.engine.determine_intent(normalize(utterance, lang), 100))
StopIteration
```

for me, this looks like normalize has a problem, but the traceback didn't say so much.
any ideas?

when i told mycroft to register, even more of this messages came. this seems to be the last fail, since it updates skills as it told me.

thx for having a look.

**Comment by hersche** [comment]
didn't saw this:
https://community.mycroft.ai/t/pairing-on-arch-linux-resolved/1549/7
could be broken down to execute this:
./msm/msm default

would be nice to have that per default or better documented..
