### ISSUE TITLE
 No module named _pocketsphinx

### ISSUE THREAD

**Issue by Ramslam007** [MycroftAI/mycroft-core#913]
i also tried multiple ways to install it like downloading package from sourceforge it seems to be installed correctly but my problem still pressists

ImportError: No module named _pocketsphinx

./start.sh audioaccuracytest
Starting audioaccuracytest
./start.sh: line 32: /root/.virtualenvs/mycroft/bin/activate: No such file or directory
2017-07-14 10:27:56,691 - mycroft.configuration - INFO - Loading configuration: /root/Desktop/mycroft-core-dev/mycroft-core-dev/mycroft/configuration/mycroft.conf
2017-07-14 10:27:56,692 - mycroft.configuration - DEBUG - Configuration '/root/Desktop/mycroft-core-dev/mycroft-core-dev/mycroft/configuration/mycroft.conf' loaded
2017-07-14 10:27:56,692 - mycroft.configuration - DEBUG - Configuration '/root/.mycroft/mycroft.conf' loaded
2017-07-14 10:27:56,692 - mycroft.configuration - INFO - Loading configuration: mycroft.ai
2017-07-14 10:27:56,695 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
2017-07-14 10:27:58,744 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device//setting HTTP/1.1" 401 38
2017-07-14 10:27:58,756 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
2017-07-14 10:28:00,462 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/auth/token HTTP/1.1" 401 38
2017-07-14 10:28:00,469 - mycroft.configuration - WARNING - Failed to fetch remote configuration: HTTPError(u'The supplied authentication is invalid',)
2017-07-14 10:28:00,470 - mycroft.configuration - INFO - Using cached configuration if available
2017-07-14 10:28:00,470 - mycroft.configuration - DEBUG - Configuration '/opt/mycroft/web_config_cache.json' not found
2017-07-14 10:28:00,470 - mycroft.configuration - INFO - Loading configuration: /etc/mycroft/mycroft.conf
2017-07-14 10:28:00,471 - mycroft.configuration - DEBUG - Configuration '/etc/mycroft/mycroft.conf' not found
2017-07-14 10:28:00,472 - mycroft.configuration - DEBUG - Configuration '/root/.mycroft/mycroft.conf' loaded
2017-07-14 10:28:00,473 - mycroft.configuration - INFO - Loading configuration: /root/.mycroft/mycroft.conf
2017-07-14 10:28:00,475 - mycroft.configuration - DEBUG - Configuration '/root/.mycroft/mycroft.conf' loaded
2017-07-14 10:28:00,477 - mycroft.configuration - DEBUG - Configuration '/root/.mycroft/mycroft.conf' loaded
Traceback (most recent call last):
  File "/root/Desktop/mycroft-core-dev/mycroft-core-dev/mycroft/audio-accuracy-test/audio_accuracy_test.py", line 10, in <module>
    from mycroft.client.speech.listener import RecognizerLoop
  File "/root/Desktop/mycroft-core-dev/mycroft-core-dev/mycroft/client/speech/listener.py", line 30, in <module>
    from mycroft.client.speech.recognizer.pocketsphinx_recognizer \
  File "/root/Desktop/mycroft-core-dev/mycroft-core-dev/mycroft/client/speech/recognizer/pocketsphinx_recognizer.py", line 24, in <module>
    from pocketsphinx import Decoder
  File "/usr/local/lib/python2.7/dist-packages/pocketsphinx/__init__.py", line 37, in <module>
    from pocketsphinx import *
  File "/usr/local/lib/python2.7/dist-packages/pocketsphinx/pocketsphinx.py", line 35, in <module>
    _pocketsphinx = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/pocketsphinx/pocketsphinx.py", line 34, in swig_import_helper
    return importlib.import_module('_pocketsphinx')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _pocketsphinx

**Comment by MatthewScholefield** [comment]
It looks like pocketsphinx didn't install correctly. Make sure to run `./dev_setup.sh`. If you've already done this, you can make it faster by running `./dev_setup.sh -sm` to skip the long process of compiling mimic.

**Comment by Ramslam007** [comment]
thanks for your quick replay but i`m completly unable to run this

>  root@svtech:~/Desktop/mycroft-core-dev/mycroft-core-dev# ./dev_setup.sh -sm
> This script should not be run as root or with sudo.

what to do bro.... i installed this packge ......  as you replied **It looks like pocketsphinx didn't install correctly**

please reply ASAP ....

**Comment by MatthewScholefield** [comment]
Well, are you installing as root? Make sure not to first run `sudo su`.

**Comment by Ramslam007** [comment]
nope.......... i use root user while login [kali linux] what to do............ please help 
thanks again

**Comment by MatthewScholefield** [comment]
If you really cannot log in as a user that is not the root account, then edit the dev_setup_debian.sh to remove the part in the beginning that checks for root.

**Comment by MatthewScholefield** [comment]
This should be fixed now since `sudo` is automatically removed if not available. Feel free to reopen if this is still an issue.
